//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * The aperture attribute provides the diameter of
 *         an opening, usually circular, that limits the quantity of light
 *         that can enter an optical instrument.
 * 
 * <p>Java class for aperture complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="aperture">
 *   <simpleContent>
 *     <extension base="<http://pds.nasa.gov/pds4/pds/v1>aperture_WO_Units">
 *       <attribute name="unit" use="required" type="{http://pds.nasa.gov/pds4/pds/v1}Units_of_Length" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aperture", propOrder = {
    "value"
})
public class Aperture {

    @XmlValue
    protected double value;
    @XmlAttribute(name = "unit", required = true)
    protected UnitsOfLength unit;

    /**
     * Gets the value of the value property.
     * 
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link UnitsOfLength }
     *     
     */
    public UnitsOfLength getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitsOfLength }
     *     
     */
    public void setUnit(UnitsOfLength value) {
        this.unit = value;
    }

}
