//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Array class defines a homogeneous
 *         N-dimensional array of scalars. The Array class is the parent
 *         class for all n-dimensional arrays of scalars.
 * 
 * <p>Java class for Array complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Array">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Byte_Stream">
 *       <sequence>
 *         <element name="offset" type="{http://pds.nasa.gov/pds4/pds/v1}offset"/>
 *         <element name="axes" type="{http://pds.nasa.gov/pds4/pds/v1}axes"/>
 *         <element name="axis_index_order" type="{http://pds.nasa.gov/pds4/pds/v1}axis_index_order"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description" minOccurs="0"/>
 *         <element name="Element_Array" type="{http://pds.nasa.gov/pds4/pds/v1}Element_Array"/>
 *         <element name="Axis_Array" type="{http://pds.nasa.gov/pds4/pds/v1}Axis_Array" maxOccurs="unbounded"/>
 *         <element name="Special_Constants" type="{http://pds.nasa.gov/pds4/pds/v1}Special_Constants" minOccurs="0"/>
 *         <element name="Object_Statistics" type="{http://pds.nasa.gov/pds4/pds/v1}Object_Statistics" minOccurs="0"/>
 *         <element ref="{http://pds.nasa.gov/pds4/pds/v1}Local_Internal_Reference" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Array", propOrder = {
    "offset",
    "axes",
    "axisIndexOrder",
    "description",
    "elementArray",
    "axisArray",
    "specialConstants",
    "objectStatistics",
    "localInternalReference"
})
@XmlSeeAlso({
    Array1D.class,
    Array2D.class,
    Array3D.class
})
public class Array
    extends ByteStream
{

    @XmlElement(required = true)
    protected Offset offset;
    @XmlSchemaType(name = "unsignedLong")
    protected int axes;
    @XmlElement(name = "axis_index_order", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String axisIndexOrder;
    protected String description;
    @XmlElement(name = "Element_Array", required = true)
    protected ElementArray elementArray;
    @XmlElement(name = "Axis_Array", required = true)
    protected List<AxisArray> axisArray;
    @XmlElement(name = "Special_Constants")
    protected SpecialConstants specialConstants;
    @XmlElement(name = "Object_Statistics")
    protected ObjectStatistics objectStatistics;
    @XmlElement(name = "Local_Internal_Reference")
    protected List<LocalInternalReference> localInternalReference;

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Offset }
     *     
     */
    public Offset getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Offset }
     *     
     */
    public void setOffset(Offset value) {
        this.offset = value;
    }

    /**
     * Gets the value of the axes property.
     * 
     */
    public int getAxes() {
        return axes;
    }

    /**
     * Sets the value of the axes property.
     * 
     */
    public void setAxes(int value) {
        this.axes = value;
    }

    /**
     * Gets the value of the axisIndexOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxisIndexOrder() {
        return axisIndexOrder;
    }

    /**
     * Sets the value of the axisIndexOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAxisIndexOrder(String value) {
        this.axisIndexOrder = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the elementArray property.
     * 
     * @return
     *     possible object is
     *     {@link ElementArray }
     *     
     */
    public ElementArray getElementArray() {
        return elementArray;
    }

    /**
     * Sets the value of the elementArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementArray }
     *     
     */
    public void setElementArray(ElementArray value) {
        this.elementArray = value;
    }

    /**
     * Gets the value of the axisArray property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the axisArray property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAxisArray().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AxisArray }
     * </p>
     * 
     * 
     * @return
     *     The value of the axisArray property.
     */
    public List<AxisArray> getAxisArray() {
        if (axisArray == null) {
            axisArray = new ArrayList<>();
        }
        return this.axisArray;
    }

    /**
     * Gets the value of the specialConstants property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialConstants }
     *     
     */
    public SpecialConstants getSpecialConstants() {
        return specialConstants;
    }

    /**
     * Sets the value of the specialConstants property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialConstants }
     *     
     */
    public void setSpecialConstants(SpecialConstants value) {
        this.specialConstants = value;
    }

    /**
     * Gets the value of the objectStatistics property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectStatistics }
     *     
     */
    public ObjectStatistics getObjectStatistics() {
        return objectStatistics;
    }

    /**
     * Sets the value of the objectStatistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectStatistics }
     *     
     */
    public void setObjectStatistics(ObjectStatistics value) {
        this.objectStatistics = value;
    }

    /**
     * Gets the value of the localInternalReference property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localInternalReference property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLocalInternalReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalInternalReference }
     * </p>
     * 
     * 
     * @return
     *     The value of the localInternalReference property.
     */
    public List<LocalInternalReference> getLocalInternalReference() {
        if (localInternalReference == null) {
            localInternalReference = new ArrayList<>();
        }
        return this.localInternalReference;
    }

}
