//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Band_Bin class specifies the characteristics
 *         of an individual spectral band in a spectral
 *         qube.
 * 
 * <p>Java class for Band_Bin complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Band_Bin">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="band_number" type="{http://pds.nasa.gov/pds4/pds/v1}band_number"/>
 *         <element name="band_width" type="{http://pds.nasa.gov/pds4/pds/v1}band_width"/>
 *         <element name="center_wavelength" type="{http://pds.nasa.gov/pds4/pds/v1}center_wavelength"/>
 *         <element name="detector_number" type="{http://pds.nasa.gov/pds4/pds/v1}detector_number" minOccurs="0"/>
 *         <element name="filter_number" type="{http://pds.nasa.gov/pds4/pds/v1}filter_number" minOccurs="0"/>
 *         <element name="grating_position" type="{http://pds.nasa.gov/pds4/pds/v1}grating_position" minOccurs="0"/>
 *         <element name="original_band" type="{http://pds.nasa.gov/pds4/pds/v1}original_band" minOccurs="0"/>
 *         <element name="standard_deviation" type="{http://pds.nasa.gov/pds4/pds/v1}standard_deviation" minOccurs="0"/>
 *         <element name="scaling_factor" type="{http://pds.nasa.gov/pds4/pds/v1}scaling_factor" minOccurs="0"/>
 *         <element name="value_offset" type="{http://pds.nasa.gov/pds4/pds/v1}value_offset" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Band_Bin", propOrder = {
    "bandNumber",
    "bandWidth",
    "centerWavelength",
    "detectorNumber",
    "filterNumber",
    "gratingPosition",
    "originalBand",
    "standardDeviation",
    "scalingFactor",
    "valueOffset"
})
public class BandBin {

    @XmlElement(name = "band_number")
    @XmlSchemaType(name = "unsignedLong")
    protected int bandNumber;
    @XmlElement(name = "band_width", required = true)
    protected BandWidth bandWidth;
    @XmlElement(name = "center_wavelength", required = true)
    protected CenterWavelength centerWavelength;
    @XmlElement(name = "detector_number")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger detectorNumber;
    @XmlElement(name = "filter_number")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger filterNumber;
    @XmlElement(name = "grating_position")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger gratingPosition;
    @XmlElement(name = "original_band")
    @XmlSchemaType(name = "unsignedLong")
    protected Integer originalBand;
    @XmlElement(name = "standard_deviation")
    protected Double standardDeviation;
    @XmlElement(name = "scaling_factor")
    protected Double scalingFactor;
    @XmlElement(name = "value_offset")
    protected Double valueOffset;

    /**
     * Gets the value of the bandNumber property.
     * 
     */
    public int getBandNumber() {
        return bandNumber;
    }

    /**
     * Sets the value of the bandNumber property.
     * 
     */
    public void setBandNumber(int value) {
        this.bandNumber = value;
    }

    /**
     * Gets the value of the bandWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BandWidth }
     *     
     */
    public BandWidth getBandWidth() {
        return bandWidth;
    }

    /**
     * Sets the value of the bandWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BandWidth }
     *     
     */
    public void setBandWidth(BandWidth value) {
        this.bandWidth = value;
    }

    /**
     * Gets the value of the centerWavelength property.
     * 
     * @return
     *     possible object is
     *     {@link CenterWavelength }
     *     
     */
    public CenterWavelength getCenterWavelength() {
        return centerWavelength;
    }

    /**
     * Sets the value of the centerWavelength property.
     * 
     * @param value
     *     allowed object is
     *     {@link CenterWavelength }
     *     
     */
    public void setCenterWavelength(CenterWavelength value) {
        this.centerWavelength = value;
    }

    /**
     * Gets the value of the detectorNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDetectorNumber() {
        return detectorNumber;
    }

    /**
     * Sets the value of the detectorNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDetectorNumber(BigInteger value) {
        this.detectorNumber = value;
    }

    /**
     * Gets the value of the filterNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFilterNumber() {
        return filterNumber;
    }

    /**
     * Sets the value of the filterNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFilterNumber(BigInteger value) {
        this.filterNumber = value;
    }

    /**
     * Gets the value of the gratingPosition property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGratingPosition() {
        return gratingPosition;
    }

    /**
     * Sets the value of the gratingPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGratingPosition(BigInteger value) {
        this.gratingPosition = value;
    }

    /**
     * Gets the value of the originalBand property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOriginalBand() {
        return originalBand;
    }

    /**
     * Sets the value of the originalBand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOriginalBand(Integer value) {
        this.originalBand = value;
    }

    /**
     * Gets the value of the standardDeviation property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getStandardDeviation() {
        return standardDeviation;
    }

    /**
     * Sets the value of the standardDeviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStandardDeviation(Double value) {
        this.standardDeviation = value;
    }

    /**
     * Gets the value of the scalingFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getScalingFactor() {
        return scalingFactor;
    }

    /**
     * Sets the value of the scalingFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setScalingFactor(Double value) {
        this.scalingFactor = value;
    }

    /**
     * Gets the value of the valueOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getValueOffset() {
        return valueOffset;
    }

    /**
     * Sets the value of the valueOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setValueOffset(Double value) {
        this.valueOffset = value;
    }

}
