//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Citation_Information class provides specific
 *         fields often used in citing the product in journal articles,
 *         abstract services, and other reference
 *         contexts.
 * 
 * <p>Java class for Citation_Information complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Citation_Information">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="author_list" type="{http://pds.nasa.gov/pds4/pds/v1}author_list" minOccurs="0"/>
 *         <element name="editor_list" type="{http://pds.nasa.gov/pds4/pds/v1}editor_list" minOccurs="0"/>
 *         <element name="publication_year" type="{http://pds.nasa.gov/pds4/pds/v1}publication_year"/>
 *         <element name="keyword" type="{http://pds.nasa.gov/pds4/pds/v1}keyword" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Citation_Information", propOrder = {
    "authorList",
    "editorList",
    "publicationYear",
    "keyword",
    "description"
})
public class CitationInformation {

    @XmlElement(name = "author_list")
    protected String authorList;
    @XmlElement(name = "editor_list")
    protected String editorList;
    @XmlElement(name = "publication_year", required = true)
    protected String publicationYear;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> keyword;
    @XmlElement(required = true)
    protected String description;

    /**
     * Gets the value of the authorList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorList() {
        return authorList;
    }

    /**
     * Sets the value of the authorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorList(String value) {
        this.authorList = value;
    }

    /**
     * Gets the value of the editorList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditorList() {
        return editorList;
    }

    /**
     * Sets the value of the editorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditorList(String value) {
        this.editorList = value;
    }

    /**
     * Gets the value of the publicationYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationYear() {
        return publicationYear;
    }

    /**
     * Sets the value of the publicationYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationYear(String value) {
        this.publicationYear = value;
    }

    /**
     * Gets the value of the keyword property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyword property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getKeyword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the keyword property.
     */
    public List<String> getKeyword() {
        if (keyword == null) {
            keyword = new ArrayList<>();
        }
        return this.keyword;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
