//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Context Area provides context information
 *         for a product.
 * 
 * <p>Java class for Context_Area complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Context_Area">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="comment" type="{http://pds.nasa.gov/pds4/pds/v1}comment" minOccurs="0"/>
 *         <element name="Time_Coordinates" type="{http://pds.nasa.gov/pds4/pds/v1}Time_Coordinates" minOccurs="0"/>
 *         <element name="Primary_Result_Summary" type="{http://pds.nasa.gov/pds4/pds/v1}Primary_Result_Summary" minOccurs="0"/>
 *         <element name="Investigation_Area" type="{http://pds.nasa.gov/pds4/pds/v1}Investigation_Area" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Observing_System" type="{http://pds.nasa.gov/pds4/pds/v1}Observing_System" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Target_Identification" type="{http://pds.nasa.gov/pds4/pds/v1}Target_Identification" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Mission_Area" type="{http://pds.nasa.gov/pds4/pds/v1}Mission_Area" minOccurs="0"/>
 *         <element name="Discipline_Area" type="{http://pds.nasa.gov/pds4/pds/v1}Discipline_Area" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Context_Area", propOrder = {
    "comment",
    "timeCoordinates",
    "primaryResultSummary",
    "investigationArea",
    "observingSystem",
    "targetIdentification",
    "missionArea",
    "disciplineArea"
})
@XmlSeeAlso({
    ObservationArea.class
})
public class ContextArea {

    protected String comment;
    @XmlElement(name = "Time_Coordinates")
    protected TimeCoordinates timeCoordinates;
    @XmlElement(name = "Primary_Result_Summary")
    protected PrimaryResultSummary primaryResultSummary;
    @XmlElement(name = "Investigation_Area")
    protected List<InvestigationArea> investigationArea;
    @XmlElement(name = "Observing_System")
    protected List<ObservingSystem> observingSystem;
    @XmlElement(name = "Target_Identification")
    protected List<TargetIdentification> targetIdentification;
    @XmlElement(name = "Mission_Area")
    protected MissionArea missionArea;
    @XmlElement(name = "Discipline_Area")
    protected DisciplineArea disciplineArea;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the timeCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link TimeCoordinates }
     *     
     */
    public TimeCoordinates getTimeCoordinates() {
        return timeCoordinates;
    }

    /**
     * Sets the value of the timeCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeCoordinates }
     *     
     */
    public void setTimeCoordinates(TimeCoordinates value) {
        this.timeCoordinates = value;
    }

    /**
     * Gets the value of the primaryResultSummary property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryResultSummary }
     *     
     */
    public PrimaryResultSummary getPrimaryResultSummary() {
        return primaryResultSummary;
    }

    /**
     * Sets the value of the primaryResultSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryResultSummary }
     *     
     */
    public void setPrimaryResultSummary(PrimaryResultSummary value) {
        this.primaryResultSummary = value;
    }

    /**
     * Gets the value of the investigationArea property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the investigationArea property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getInvestigationArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvestigationArea }
     * </p>
     * 
     * 
     * @return
     *     The value of the investigationArea property.
     */
    public List<InvestigationArea> getInvestigationArea() {
        if (investigationArea == null) {
            investigationArea = new ArrayList<>();
        }
        return this.investigationArea;
    }

    /**
     * Gets the value of the observingSystem property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the observingSystem property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getObservingSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObservingSystem }
     * </p>
     * 
     * 
     * @return
     *     The value of the observingSystem property.
     */
    public List<ObservingSystem> getObservingSystem() {
        if (observingSystem == null) {
            observingSystem = new ArrayList<>();
        }
        return this.observingSystem;
    }

    /**
     * Gets the value of the targetIdentification property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetIdentification property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTargetIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TargetIdentification }
     * </p>
     * 
     * 
     * @return
     *     The value of the targetIdentification property.
     */
    public List<TargetIdentification> getTargetIdentification() {
        if (targetIdentification == null) {
            targetIdentification = new ArrayList<>();
        }
        return this.targetIdentification;
    }

    /**
     * Gets the value of the missionArea property.
     * 
     * @return
     *     possible object is
     *     {@link MissionArea }
     *     
     */
    public MissionArea getMissionArea() {
        return missionArea;
    }

    /**
     * Sets the value of the missionArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link MissionArea }
     *     
     */
    public void setMissionArea(MissionArea value) {
        this.missionArea = value;
    }

    /**
     * Gets the value of the disciplineArea property.
     * 
     * @return
     *     possible object is
     *     {@link DisciplineArea }
     *     
     */
    public DisciplineArea getDisciplineArea() {
        return disciplineArea;
    }

    /**
     * Sets the value of the disciplineArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisciplineArea }
     *     
     */
    public void setDisciplineArea(DisciplineArea value) {
        this.disciplineArea = value;
    }

}
