//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Data Set PDS3 class is used to capture the
 *         data set information from the PDS3 Data Set
 *         Catalog.
 * 
 * <p>Java class for Data_Set_PDS3 complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Data_Set_PDS3">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="data_set_id" type="{http://pds.nasa.gov/pds4/pds/v1}data_set_id"/>
 *         <element name="data_set_name" type="{http://pds.nasa.gov/pds4/pds/v1}data_set_name"/>
 *         <element name="data_set_release_date" type="{http://pds.nasa.gov/pds4/pds/v1}data_set_release_date"/>
 *         <element name="start_time" type="{http://pds.nasa.gov/pds4/pds/v1}start_time" minOccurs="0"/>
 *         <element name="start_date_time" type="{http://pds.nasa.gov/pds4/pds/v1}start_date_time" minOccurs="0"/>
 *         <element name="stop_time" type="{http://pds.nasa.gov/pds4/pds/v1}stop_time" minOccurs="0"/>
 *         <element name="stop_date_time" type="{http://pds.nasa.gov/pds4/pds/v1}stop_date_time" minOccurs="0"/>
 *         <element name="producer_full_name" type="{http://pds.nasa.gov/pds4/pds/v1}producer_full_name"/>
 *         <element name="citation_text" type="{http://pds.nasa.gov/pds4/pds/v1}citation_text"/>
 *         <element name="data_set_terse_desc" type="{http://pds.nasa.gov/pds4/pds/v1}data_set_terse_desc"/>
 *         <element name="abstract_desc" type="{http://pds.nasa.gov/pds4/pds/v1}abstract_desc"/>
 *         <element name="data_set_desc" type="{http://pds.nasa.gov/pds4/pds/v1}data_set_desc"/>
 *         <element name="confidence_level_note" type="{http://pds.nasa.gov/pds4/pds/v1}confidence_level_note"/>
 *         <element name="archive_status" type="{http://pds.nasa.gov/pds4/pds/v1}archive_status"/>
 *         <element name="NSSDC" type="{http://pds.nasa.gov/pds4/pds/v1}NSSDC" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Data_Set_PDS3", propOrder = {
    "dataSetId",
    "dataSetName",
    "dataSetReleaseDate",
    "startTime",
    "startDateTime",
    "stopTime",
    "stopDateTime",
    "producerFullName",
    "citationText",
    "dataSetTerseDesc",
    "abstractDesc",
    "dataSetDesc",
    "confidenceLevelNote",
    "archiveStatus",
    "nssdc"
})
public class DataSetPDS3 {

    @XmlElement(name = "data_set_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String dataSetId;
    @XmlElement(name = "data_set_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String dataSetName;
    @XmlElement(name = "data_set_release_date", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String dataSetReleaseDate;
    @XmlElementRef(name = "start_time", namespace = "http://pds.nasa.gov/pds4/pds/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<StartTime> startTime;
    @XmlElementRef(name = "start_date_time", namespace = "http://pds.nasa.gov/pds4/pds/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<StartDateTime> startDateTime;
    @XmlElementRef(name = "stop_time", namespace = "http://pds.nasa.gov/pds4/pds/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<StopTime> stopTime;
    @XmlElementRef(name = "stop_date_time", namespace = "http://pds.nasa.gov/pds4/pds/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<StopDateTime> stopDateTime;
    @XmlElement(name = "producer_full_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String producerFullName;
    @XmlElement(name = "citation_text", required = true)
    protected String citationText;
    @XmlElement(name = "data_set_terse_desc", required = true)
    protected String dataSetTerseDesc;
    @XmlElement(name = "abstract_desc", required = true)
    protected String abstractDesc;
    @XmlElement(name = "data_set_desc", required = true)
    protected String dataSetDesc;
    @XmlElement(name = "confidence_level_note", required = true)
    protected String confidenceLevelNote;
    @XmlElement(name = "archive_status", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String archiveStatus;
    @XmlElement(name = "NSSDC")
    protected List<NSSDC> nssdc;

    /**
     * Gets the value of the dataSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSetId() {
        return dataSetId;
    }

    /**
     * Sets the value of the dataSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSetId(String value) {
        this.dataSetId = value;
    }

    /**
     * Gets the value of the dataSetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSetName() {
        return dataSetName;
    }

    /**
     * Sets the value of the dataSetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSetName(String value) {
        this.dataSetName = value;
    }

    /**
     * Gets the value of the dataSetReleaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSetReleaseDate() {
        return dataSetReleaseDate;
    }

    /**
     * Sets the value of the dataSetReleaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSetReleaseDate(String value) {
        this.dataSetReleaseDate = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link StartTime }{@code >}
     *     
     */
    public JAXBElement<StartTime> getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link StartTime }{@code >}
     *     
     */
    public void setStartTime(JAXBElement<StartTime> value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the startDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link StartDateTime }{@code >}
     *     
     */
    public JAXBElement<StartDateTime> getStartDateTime() {
        return startDateTime;
    }

    /**
     * Sets the value of the startDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link StartDateTime }{@code >}
     *     
     */
    public void setStartDateTime(JAXBElement<StartDateTime> value) {
        this.startDateTime = value;
    }

    /**
     * Gets the value of the stopTime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link StopTime }{@code >}
     *     
     */
    public JAXBElement<StopTime> getStopTime() {
        return stopTime;
    }

    /**
     * Sets the value of the stopTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link StopTime }{@code >}
     *     
     */
    public void setStopTime(JAXBElement<StopTime> value) {
        this.stopTime = value;
    }

    /**
     * Gets the value of the stopDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link StopDateTime }{@code >}
     *     
     */
    public JAXBElement<StopDateTime> getStopDateTime() {
        return stopDateTime;
    }

    /**
     * Sets the value of the stopDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link StopDateTime }{@code >}
     *     
     */
    public void setStopDateTime(JAXBElement<StopDateTime> value) {
        this.stopDateTime = value;
    }

    /**
     * Gets the value of the producerFullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducerFullName() {
        return producerFullName;
    }

    /**
     * Sets the value of the producerFullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducerFullName(String value) {
        this.producerFullName = value;
    }

    /**
     * Gets the value of the citationText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitationText() {
        return citationText;
    }

    /**
     * Sets the value of the citationText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitationText(String value) {
        this.citationText = value;
    }

    /**
     * Gets the value of the dataSetTerseDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSetTerseDesc() {
        return dataSetTerseDesc;
    }

    /**
     * Sets the value of the dataSetTerseDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSetTerseDesc(String value) {
        this.dataSetTerseDesc = value;
    }

    /**
     * Gets the value of the abstractDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstractDesc() {
        return abstractDesc;
    }

    /**
     * Sets the value of the abstractDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstractDesc(String value) {
        this.abstractDesc = value;
    }

    /**
     * Gets the value of the dataSetDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSetDesc() {
        return dataSetDesc;
    }

    /**
     * Sets the value of the dataSetDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSetDesc(String value) {
        this.dataSetDesc = value;
    }

    /**
     * Gets the value of the confidenceLevelNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfidenceLevelNote() {
        return confidenceLevelNote;
    }

    /**
     * Sets the value of the confidenceLevelNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfidenceLevelNote(String value) {
        this.confidenceLevelNote = value;
    }

    /**
     * Gets the value of the archiveStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchiveStatus() {
        return archiveStatus;
    }

    /**
     * Sets the value of the archiveStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchiveStatus(String value) {
        this.archiveStatus = value;
    }

    /**
     * Gets the value of the nssdc property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nssdc property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNSSDC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NSSDC }
     * </p>
     * 
     * 
     * @return
     *     The value of the nssdc property.
     */
    public List<NSSDC> getNSSDC() {
        if (nssdc == null) {
            nssdc = new ArrayList<>();
        }
        return this.nssdc;
    }

}
