//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The DD_Association class defines the association
 *         between two classes or a class and an attribute in a data
 *         dictionary.
 * 
 * <p>Java class for DD_Association complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="DD_Association">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="identifier_reference" type="{http://pds.nasa.gov/pds4/pds/v1}identifier_reference" maxOccurs="unbounded"/>
 *         <element name="local_identifier" type="{http://pds.nasa.gov/pds4/pds/v1}local_identifier" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="reference_type" type="{http://pds.nasa.gov/pds4/pds/v1}reference_type"/>
 *         <element name="minimum_occurrences" type="{http://pds.nasa.gov/pds4/pds/v1}minimum_occurrences"/>
 *         <element name="maximum_occurrences" type="{http://pds.nasa.gov/pds4/pds/v1}maximum_occurrences"/>
 *         <element name="constant_value" type="{http://pds.nasa.gov/pds4/pds/v1}constant_value" minOccurs="0"/>
 *         <element name="DD_Attribute_Reference" type="{http://pds.nasa.gov/pds4/pds/v1}DD_Attribute_Reference" minOccurs="0"/>
 *         <element name="DD_Class_Reference" type="{http://pds.nasa.gov/pds4/pds/v1}DD_Class_Reference" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DD_Association", propOrder = {
    "identifierReference",
    "localIdentifier",
    "referenceType",
    "minimumOccurrences",
    "maximumOccurrences",
    "constantValue",
    "ddAttributeReference",
    "ddClassReference"
})
public class DDAssociation {

    @XmlElement(name = "identifier_reference", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> identifierReference;
    @XmlElementRef(name = "local_identifier", namespace = "http://pds.nasa.gov/pds4/pds/v1", type = JAXBElement.class, required = false)
    protected List<JAXBElement<String>> localIdentifier;
    @XmlElement(name = "reference_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String referenceType;
    @XmlElement(name = "minimum_occurrences", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String minimumOccurrences;
    @XmlElement(name = "maximum_occurrences", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String maximumOccurrences;
    @XmlElement(name = "constant_value")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String constantValue;
    @XmlElement(name = "DD_Attribute_Reference")
    protected DDAttributeReference ddAttributeReference;
    @XmlElement(name = "DD_Class_Reference")
    protected DDClassReference ddClassReference;

    /**
     * Gets the value of the identifierReference property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifierReference property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getIdentifierReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the identifierReference property.
     */
    public List<String> getIdentifierReference() {
        if (identifierReference == null) {
            identifierReference = new ArrayList<>();
        }
        return this.identifierReference;
    }

    /**
     * Gets the value of the localIdentifier property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localIdentifier property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLocalIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * </p>
     * 
     * 
     * @return
     *     The value of the localIdentifier property.
     */
    public List<JAXBElement<String>> getLocalIdentifier() {
        if (localIdentifier == null) {
            localIdentifier = new ArrayList<>();
        }
        return this.localIdentifier;
    }

    /**
     * Gets the value of the referenceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceType() {
        return referenceType;
    }

    /**
     * Sets the value of the referenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceType(String value) {
        this.referenceType = value;
    }

    /**
     * Gets the value of the minimumOccurrences property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumOccurrences() {
        return minimumOccurrences;
    }

    /**
     * Sets the value of the minimumOccurrences property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumOccurrences(String value) {
        this.minimumOccurrences = value;
    }

    /**
     * Gets the value of the maximumOccurrences property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumOccurrences() {
        return maximumOccurrences;
    }

    /**
     * Sets the value of the maximumOccurrences property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumOccurrences(String value) {
        this.maximumOccurrences = value;
    }

    /**
     * Gets the value of the constantValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConstantValue() {
        return constantValue;
    }

    /**
     * Sets the value of the constantValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConstantValue(String value) {
        this.constantValue = value;
    }

    /**
     * Gets the value of the ddAttributeReference property.
     * 
     * @return
     *     possible object is
     *     {@link DDAttributeReference }
     *     
     */
    public DDAttributeReference getDDAttributeReference() {
        return ddAttributeReference;
    }

    /**
     * Sets the value of the ddAttributeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DDAttributeReference }
     *     
     */
    public void setDDAttributeReference(DDAttributeReference value) {
        this.ddAttributeReference = value;
    }

    /**
     * Gets the value of the ddClassReference property.
     * 
     * @return
     *     possible object is
     *     {@link DDClassReference }
     *     
     */
    public DDClassReference getDDClassReference() {
        return ddClassReference;
    }

    /**
     * Sets the value of the ddClassReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DDClassReference }
     *     
     */
    public void setDDClassReference(DDClassReference value) {
        this.ddClassReference = value;
    }

}
