//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The DD_Rule class defines a Schematron rule for
 *         a data dictionary.
 * 
 * <p>Java class for DD_Rule complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="DD_Rule">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="local_identifier" type="{http://pds.nasa.gov/pds4/pds/v1}local_identifier"/>
 *         <element name="rule_context" type="{http://pds.nasa.gov/pds4/pds/v1}rule_context"/>
 *         <element name="rule_assign" type="{http://pds.nasa.gov/pds4/pds/v1}rule_assign" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="DD_Attribute_Reference" type="{http://pds.nasa.gov/pds4/pds/v1}DD_Attribute_Reference" minOccurs="0"/>
 *         <element name="DD_Class_Reference" type="{http://pds.nasa.gov/pds4/pds/v1}DD_Class_Reference" minOccurs="0"/>
 *         <element name="DD_Rule_Statement" type="{http://pds.nasa.gov/pds4/pds/v1}DD_Rule_Statement" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DD_Rule", propOrder = {
    "localIdentifier",
    "ruleContext",
    "ruleAssign",
    "ddAttributeReference",
    "ddClassReference",
    "ddRuleStatement"
})
public class DDRule {

    @XmlElement(name = "local_identifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String localIdentifier;
    @XmlElement(name = "rule_context", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String ruleContext;
    @XmlElement(name = "rule_assign")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> ruleAssign;
    @XmlElement(name = "DD_Attribute_Reference")
    protected DDAttributeReference ddAttributeReference;
    @XmlElement(name = "DD_Class_Reference")
    protected DDClassReference ddClassReference;
    @XmlElement(name = "DD_Rule_Statement", required = true)
    protected List<DDRuleStatement> ddRuleStatement;

    /**
     * Gets the value of the localIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalIdentifier() {
        return localIdentifier;
    }

    /**
     * Sets the value of the localIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalIdentifier(String value) {
        this.localIdentifier = value;
    }

    /**
     * Gets the value of the ruleContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuleContext() {
        return ruleContext;
    }

    /**
     * Sets the value of the ruleContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuleContext(String value) {
        this.ruleContext = value;
    }

    /**
     * Gets the value of the ruleAssign property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ruleAssign property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getRuleAssign().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the ruleAssign property.
     */
    public List<String> getRuleAssign() {
        if (ruleAssign == null) {
            ruleAssign = new ArrayList<>();
        }
        return this.ruleAssign;
    }

    /**
     * Gets the value of the ddAttributeReference property.
     * 
     * @return
     *     possible object is
     *     {@link DDAttributeReference }
     *     
     */
    public DDAttributeReference getDDAttributeReference() {
        return ddAttributeReference;
    }

    /**
     * Sets the value of the ddAttributeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DDAttributeReference }
     *     
     */
    public void setDDAttributeReference(DDAttributeReference value) {
        this.ddAttributeReference = value;
    }

    /**
     * Gets the value of the ddClassReference property.
     * 
     * @return
     *     possible object is
     *     {@link DDClassReference }
     *     
     */
    public DDClassReference getDDClassReference() {
        return ddClassReference;
    }

    /**
     * Sets the value of the ddClassReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DDClassReference }
     *     
     */
    public void setDDClassReference(DDClassReference value) {
        this.ddClassReference = value;
    }

    /**
     * Gets the value of the ddRuleStatement property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ddRuleStatement property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDDRuleStatement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DDRuleStatement }
     * </p>
     * 
     * 
     * @return
     *     The value of the ddRuleStatement property.
     */
    public List<DDRuleStatement> getDDRuleStatement() {
        if (ddRuleStatement == null) {
            ddRuleStatement = new ArrayList<>();
        }
        return this.ddRuleStatement;
    }

}
