//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The DD_Value_Domain_Full class provides a more
 *         complete definition of a attribute's value
 *         domain.
 * 
 * <p>Java class for DD_Value_Domain_Full complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="DD_Value_Domain_Full">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="enumeration_flag" type="{http://pds.nasa.gov/pds4/pds/v1}enumeration_flag"/>
 *         <element name="value_data_type" type="{http://pds.nasa.gov/pds4/pds/v1}value_data_type"/>
 *         <element name="formation_rule" type="{http://pds.nasa.gov/pds4/pds/v1}formation_rule" minOccurs="0"/>
 *         <element name="minimum_characters" type="{http://pds.nasa.gov/pds4/pds/v1}minimum_characters" minOccurs="0"/>
 *         <element name="maximum_characters" type="{http://pds.nasa.gov/pds4/pds/v1}maximum_characters" minOccurs="0"/>
 *         <element name="minimum_value" type="{http://pds.nasa.gov/pds4/pds/v1}minimum_value" minOccurs="0"/>
 *         <element name="maximum_value" type="{http://pds.nasa.gov/pds4/pds/v1}maximum_value" minOccurs="0"/>
 *         <element name="pattern" type="{http://pds.nasa.gov/pds4/pds/v1}pattern" minOccurs="0"/>
 *         <element name="unit_of_measure_type" type="{http://pds.nasa.gov/pds4/pds/v1}unit_of_measure_type" minOccurs="0"/>
 *         <element name="conceptual_domain" type="{http://pds.nasa.gov/pds4/pds/v1}conceptual_domain"/>
 *         <element name="specified_unit_id" type="{http://pds.nasa.gov/pds4/pds/v1}specified_unit_id" minOccurs="0"/>
 *         <element name="DD_Permissible_Value_Full" type="{http://pds.nasa.gov/pds4/pds/v1}DD_Permissible_Value_Full" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DD_Value_Domain_Full", propOrder = {
    "enumerationFlag",
    "valueDataType",
    "formationRule",
    "minimumCharacters",
    "maximumCharacters",
    "minimumValue",
    "maximumValue",
    "pattern",
    "unitOfMeasureType",
    "conceptualDomain",
    "specifiedUnitId",
    "ddPermissibleValueFull"
})
public class DDValueDomainFull {

    @XmlElement(name = "enumeration_flag")
    protected boolean enumerationFlag;
    @XmlElement(name = "value_data_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String valueDataType;
    @XmlElement(name = "formation_rule")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String formationRule;
    @XmlElement(name = "minimum_characters")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String minimumCharacters;
    @XmlElement(name = "maximum_characters")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String maximumCharacters;
    @XmlElement(name = "minimum_value")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String minimumValue;
    @XmlElement(name = "maximum_value")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String maximumValue;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String pattern;
    @XmlElement(name = "unit_of_measure_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String unitOfMeasureType;
    @XmlElement(name = "conceptual_domain", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String conceptualDomain;
    @XmlElement(name = "specified_unit_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String specifiedUnitId;
    @XmlElement(name = "DD_Permissible_Value_Full")
    protected List<DDPermissibleValueFull> ddPermissibleValueFull;

    /**
     * Gets the value of the enumerationFlag property.
     * 
     */
    public boolean isEnumerationFlag() {
        return enumerationFlag;
    }

    /**
     * Sets the value of the enumerationFlag property.
     * 
     */
    public void setEnumerationFlag(boolean value) {
        this.enumerationFlag = value;
    }

    /**
     * Gets the value of the valueDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueDataType() {
        return valueDataType;
    }

    /**
     * Sets the value of the valueDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueDataType(String value) {
        this.valueDataType = value;
    }

    /**
     * Gets the value of the formationRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormationRule() {
        return formationRule;
    }

    /**
     * Sets the value of the formationRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormationRule(String value) {
        this.formationRule = value;
    }

    /**
     * Gets the value of the minimumCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumCharacters() {
        return minimumCharacters;
    }

    /**
     * Sets the value of the minimumCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumCharacters(String value) {
        this.minimumCharacters = value;
    }

    /**
     * Gets the value of the maximumCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumCharacters() {
        return maximumCharacters;
    }

    /**
     * Sets the value of the maximumCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumCharacters(String value) {
        this.maximumCharacters = value;
    }

    /**
     * Gets the value of the minimumValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumValue() {
        return minimumValue;
    }

    /**
     * Sets the value of the minimumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumValue(String value) {
        this.minimumValue = value;
    }

    /**
     * Gets the value of the maximumValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumValue() {
        return maximumValue;
    }

    /**
     * Sets the value of the maximumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumValue(String value) {
        this.maximumValue = value;
    }

    /**
     * Gets the value of the pattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPattern(String value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the unitOfMeasureType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasureType() {
        return unitOfMeasureType;
    }

    /**
     * Sets the value of the unitOfMeasureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasureType(String value) {
        this.unitOfMeasureType = value;
    }

    /**
     * Gets the value of the conceptualDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConceptualDomain() {
        return conceptualDomain;
    }

    /**
     * Sets the value of the conceptualDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConceptualDomain(String value) {
        this.conceptualDomain = value;
    }

    /**
     * Gets the value of the specifiedUnitId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecifiedUnitId() {
        return specifiedUnitId;
    }

    /**
     * Sets the value of the specifiedUnitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecifiedUnitId(String value) {
        this.specifiedUnitId = value;
    }

    /**
     * Gets the value of the ddPermissibleValueFull property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ddPermissibleValueFull property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDDPermissibleValueFull().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DDPermissibleValueFull }
     * </p>
     * 
     * 
     * @return
     *     The value of the ddPermissibleValueFull property.
     */
    public List<DDPermissibleValueFull> getDDPermissibleValueFull() {
        if (ddPermissibleValueFull == null) {
            ddPermissibleValueFull = new ArrayList<>();
        }
        return this.ddPermissibleValueFull;
    }

}
