//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Document class describes a
 *         document.
 * 
 * <p>Java class for Document complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Document">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="revision_id" type="{http://pds.nasa.gov/pds4/pds/v1}revision_id" minOccurs="0"/>
 *         <element name="document_name" type="{http://pds.nasa.gov/pds4/pds/v1}document_name" minOccurs="0"/>
 *         <element name="doi" type="{http://pds.nasa.gov/pds4/pds/v1}doi" minOccurs="0"/>
 *         <element name="author_list" type="{http://pds.nasa.gov/pds4/pds/v1}author_list" minOccurs="0"/>
 *         <element name="editor_list" type="{http://pds.nasa.gov/pds4/pds/v1}editor_list" minOccurs="0"/>
 *         <element name="acknowledgement_text" type="{http://pds.nasa.gov/pds4/pds/v1}acknowledgement_text" minOccurs="0"/>
 *         <element name="copyright" type="{http://pds.nasa.gov/pds4/pds/v1}copyright" minOccurs="0"/>
 *         <element name="publication_date" type="{http://pds.nasa.gov/pds4/pds/v1}publication_date"/>
 *         <element name="document_editions" type="{http://pds.nasa.gov/pds4/pds/v1}document_editions" minOccurs="0"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description" minOccurs="0"/>
 *         <element name="Document_Edition" type="{http://pds.nasa.gov/pds4/pds/v1}Document_Edition" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "revisionId",
    "documentName",
    "doi",
    "authorList",
    "editorList",
    "acknowledgementText",
    "copyright",
    "publicationDate",
    "documentEditions",
    "description",
    "documentEdition"
})
public class Document {

    @XmlElement(name = "revision_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String revisionId;
    @XmlElement(name = "document_name")
    protected String documentName;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String doi;
    @XmlElement(name = "author_list")
    protected String authorList;
    @XmlElement(name = "editor_list")
    protected String editorList;
    @XmlElement(name = "acknowledgement_text")
    protected String acknowledgementText;
    protected String copyright;
    @XmlElement(name = "publication_date", required = true, nillable = true)
    protected PublicationDate publicationDate;
    @XmlElement(name = "document_editions")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger documentEditions;
    protected String description;
    @XmlElement(name = "Document_Edition", required = true)
    protected List<DocumentEdition> documentEdition;

    /**
     * Gets the value of the revisionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionId() {
        return revisionId;
    }

    /**
     * Sets the value of the revisionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionId(String value) {
        this.revisionId = value;
    }

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentName(String value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the doi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoi() {
        return doi;
    }

    /**
     * Sets the value of the doi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoi(String value) {
        this.doi = value;
    }

    /**
     * Gets the value of the authorList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorList() {
        return authorList;
    }

    /**
     * Sets the value of the authorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorList(String value) {
        this.authorList = value;
    }

    /**
     * Gets the value of the editorList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditorList() {
        return editorList;
    }

    /**
     * Sets the value of the editorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditorList(String value) {
        this.editorList = value;
    }

    /**
     * Gets the value of the acknowledgementText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcknowledgementText() {
        return acknowledgementText;
    }

    /**
     * Sets the value of the acknowledgementText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcknowledgementText(String value) {
        this.acknowledgementText = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the publicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationDate }
     *     
     */
    public PublicationDate getPublicationDate() {
        return publicationDate;
    }

    /**
     * Sets the value of the publicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationDate }
     *     
     */
    public void setPublicationDate(PublicationDate value) {
        this.publicationDate = value;
    }

    /**
     * Gets the value of the documentEditions property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDocumentEditions() {
        return documentEditions;
    }

    /**
     * Sets the value of the documentEditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDocumentEditions(BigInteger value) {
        this.documentEditions = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the documentEdition property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentEdition property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDocumentEdition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentEdition }
     * </p>
     * 
     * 
     * @return
     *     The value of the documentEdition property.
     */
    public List<DocumentEdition> getDocumentEdition() {
        if (documentEdition == null) {
            documentEdition = new ArrayList<>();
        }
        return this.documentEdition;
    }

}
