//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Encoded Byte Stream class defines byte
 *         streams that must be decoded by software before use. These byte
 *         streams must only use standard encodings. The Encoded Byte
 *         Stream class is the parent class for all encoded byte
 *         streams.
 * 
 * <p>Java class for Encoded_Byte_Stream complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Encoded_Byte_Stream">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Byte_Stream">
 *       <sequence>
 *         <element name="offset" type="{http://pds.nasa.gov/pds4/pds/v1}offset"/>
 *         <element name="object_length" type="{http://pds.nasa.gov/pds4/pds/v1}object_length" minOccurs="0"/>
 *         <element name="encoding_standard_id" type="{http://pds.nasa.gov/pds4/pds/v1}encoding_standard_id"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Encoded_Byte_Stream", propOrder = {
    "offset",
    "objectLength",
    "encodingStandardId",
    "description"
})
@XmlSeeAlso({
    EncodedBinary.class,
    EncodedHeader.class,
    EncodedImage.class,
    EncodedNative.class
})
public class EncodedByteStream
    extends ByteStream
{

    @XmlElement(required = true)
    protected Offset offset;
    @XmlElement(name = "object_length")
    protected ObjectLength objectLength;
    @XmlElement(name = "encoding_standard_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String encodingStandardId;
    protected String description;

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Offset }
     *     
     */
    public Offset getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Offset }
     *     
     */
    public void setOffset(Offset value) {
        this.offset = value;
    }

    /**
     * Gets the value of the objectLength property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectLength }
     *     
     */
    public ObjectLength getObjectLength() {
        return objectLength;
    }

    /**
     * Sets the value of the objectLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectLength }
     *     
     */
    public void setObjectLength(ObjectLength value) {
        this.objectLength = value;
    }

    /**
     * Gets the value of the encodingStandardId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncodingStandardId() {
        return encodingStandardId;
    }

    /**
     * Sets the value of the encodingStandardId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncodingStandardId(String value) {
        this.encodingStandardId = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
