//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The File Area Transfer Manifest class describes
 *         a file that contains a two column table that maps the logical
 *         identifiers and version ids of products to their file
 *         specification names.
 * 
 * <p>Java class for File_Area_Transfer_Manifest complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="File_Area_Transfer_Manifest">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}File_Area">
 *       <sequence>
 *         <element name="File" type="{http://pds.nasa.gov/pds4/pds/v1}File"/>
 *         <element name="Transfer_Manifest" type="{http://pds.nasa.gov/pds4/pds/v1}Transfer_Manifest"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "File_Area_Transfer_Manifest", propOrder = {
    "file",
    "transferManifest"
})
public class FileAreaTransferManifest
    extends FileArea
{

    @XmlElement(name = "File", required = true)
    protected File file;
    @XmlElement(name = "Transfer_Manifest", required = true)
    protected TransferManifest transferManifest;

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link File }
     *     
     */
    public File getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link File }
     *     
     */
    public void setFile(File value) {
        this.file = value;
    }

    /**
     * Gets the value of the transferManifest property.
     * 
     * @return
     *     possible object is
     *     {@link TransferManifest }
     *     
     */
    public TransferManifest getTransferManifest() {
        return transferManifest;
    }

    /**
     * Sets the value of the transferManifest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferManifest }
     *     
     */
    public void setTransferManifest(TransferManifest value) {
        this.transferManifest = value;
    }

}
