//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The File Area SPICE Kernel class describes a
 *         file that contains a SPICE Kernel object.
 * 
 * <p>Java class for File_Area_SPICE_Kernel complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="File_Area_SPICE_Kernel">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}File_Area">
 *       <sequence>
 *         <element name="File" type="{http://pds.nasa.gov/pds4/pds/v1}File"/>
 *         <element name="SPICE_Kernel" type="{http://pds.nasa.gov/pds4/pds/v1}SPICE_Kernel"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "File_Area_SPICE_Kernel", propOrder = {
    "file",
    "spiceKernel"
})
public class FileAreaSPICEKernel
    extends FileArea
{

    @XmlElement(name = "File", required = true)
    protected File file;
    @XmlElement(name = "SPICE_Kernel", required = true)
    protected SPICEKernel spiceKernel;

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link File }
     *     
     */
    public File getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link File }
     *     
     */
    public void setFile(File value) {
        this.file = value;
    }

    /**
     * Gets the value of the spiceKernel property.
     * 
     * @return
     *     possible object is
     *     {@link SPICEKernel }
     *     
     */
    public SPICEKernel getSPICEKernel() {
        return spiceKernel;
    }

    /**
     * Sets the value of the spiceKernel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPICEKernel }
     *     
     */
    public void setSPICEKernel(SPICEKernel value) {
        this.spiceKernel = value;
    }

}
