//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The File Area Metadata class describes a table
 *         which provides new, and/or improved, metadata. All field names
 *         provided must be attributes defined in PDS4, either in the
 *         common dictionary, or in a PDS4 discipline or mission
 *         dictionary.
 * 
 * <p>Java class for File_Area_Metadata complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="File_Area_Metadata">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}File_Area">
 *       <sequence>
 *         <element name="File" type="{http://pds.nasa.gov/pds4/pds/v1}File"/>
 *         <element name="Header" type="{http://pds.nasa.gov/pds4/pds/v1}Header" minOccurs="0"/>
 *         <choice>
 *           <element name="Table_Character" type="{http://pds.nasa.gov/pds4/pds/v1}Table_Character"/>
 *           <element name="Table_Delimited" type="{http://pds.nasa.gov/pds4/pds/v1}Table_Delimited"/>
 *         </choice>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "File_Area_Metadata", propOrder = {
    "file",
    "header",
    "tableCharacter",
    "tableDelimited"
})
public class FileAreaMetadata
    extends FileArea
{

    @XmlElement(name = "File", required = true)
    protected File file;
    @XmlElement(name = "Header")
    protected Header header;
    @XmlElement(name = "Table_Character")
    protected TableCharacter tableCharacter;
    @XmlElement(name = "Table_Delimited")
    protected TableDelimited tableDelimited;

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link File }
     *     
     */
    public File getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link File }
     *     
     */
    public void setFile(File value) {
        this.file = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the tableCharacter property.
     * 
     * @return
     *     possible object is
     *     {@link TableCharacter }
     *     
     */
    public TableCharacter getTableCharacter() {
        return tableCharacter;
    }

    /**
     * Sets the value of the tableCharacter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableCharacter }
     *     
     */
    public void setTableCharacter(TableCharacter value) {
        this.tableCharacter = value;
    }

    /**
     * Gets the value of the tableDelimited property.
     * 
     * @return
     *     possible object is
     *     {@link TableDelimited }
     *     
     */
    public TableDelimited getTableDelimited() {
        return tableDelimited;
    }

    /**
     * Sets the value of the tableDelimited property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableDelimited }
     *     
     */
    public void setTableDelimited(TableDelimited value) {
        this.tableDelimited = value;
    }

}
