//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The File Area Inventory class describes a file
 *         and an inventory consisting of references to 
 *         members.
 * 
 * <p>Java class for File_Area_Inventory complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="File_Area_Inventory">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}File_Area">
 *       <sequence>
 *         <element name="File" type="{http://pds.nasa.gov/pds4/pds/v1}File"/>
 *         <element name="Inventory" type="{http://pds.nasa.gov/pds4/pds/v1}Inventory"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "File_Area_Inventory", propOrder = {
    "file",
    "inventory"
})
public class FileAreaInventory
    extends FileArea
{

    @XmlElement(name = "File", required = true)
    protected File file;
    @XmlElement(name = "Inventory", required = true)
    protected Inventory inventory;

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link File }
     *     
     */
    public File getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link File }
     *     
     */
    public void setFile(File value) {
        this.file = value;
    }

    /**
     * Gets the value of the inventory property.
     * 
     * @return
     *     possible object is
     *     {@link Inventory }
     *     
     */
    public Inventory getInventory() {
        return inventory;
    }

    /**
     * Sets the value of the inventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inventory }
     *     
     */
    public void setInventory(Inventory value) {
        this.inventory = value;
    }

}
