//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Field_Group_Delimited class allows a group
 *         of delimited fields.
 * 
 * <p>Java class for Group_Field_Delimited complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Group_Field_Delimited">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Group">
 *       <sequence>
 *         <choice maxOccurs="unbounded">
 *           <element name="Field_Delimited" type="{http://pds.nasa.gov/pds4/pds/v1}Field_Delimited"/>
 *           <element name="Group_Field_Delimited" type="{http://pds.nasa.gov/pds4/pds/v1}Group_Field_Delimited"/>
 *         </choice>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Group_Field_Delimited", propOrder = {
    "fieldDelimitedOrGroupFieldDelimited"
})
public class GroupFieldDelimited
    extends Group
{

    @XmlElements({
        @XmlElement(name = "Field_Delimited", type = FieldDelimited.class),
        @XmlElement(name = "Group_Field_Delimited", type = GroupFieldDelimited.class)
    })
    protected List<Object> fieldDelimitedOrGroupFieldDelimited;

    /**
     * Gets the value of the fieldDelimitedOrGroupFieldDelimited property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldDelimitedOrGroupFieldDelimited property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getFieldDelimitedOrGroupFieldDelimited().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldDelimited }
     * {@link GroupFieldDelimited }
     * </p>
     * 
     * 
     * @return
     *     The value of the fieldDelimitedOrGroupFieldDelimited property.
     */
    public List<Object> getFieldDelimitedOrGroupFieldDelimited() {
        if (fieldDelimitedOrGroupFieldDelimited == null) {
            fieldDelimitedOrGroupFieldDelimited = new ArrayList<>();
        }
        return this.fieldDelimitedOrGroupFieldDelimited;
    }

}
