//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The identification area consists of attributes
 *         that identify and name an object.
 * 
 * <p>Java class for Identification_Area complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Identification_Area">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="logical_identifier" type="{http://pds.nasa.gov/pds4/pds/v1}logical_identifier"/>
 *         <element name="version_id" type="{http://pds.nasa.gov/pds4/pds/v1}version_id"/>
 *         <element name="title" type="{http://pds.nasa.gov/pds4/pds/v1}title"/>
 *         <element name="information_model_version" type="{http://pds.nasa.gov/pds4/pds/v1}information_model_version"/>
 *         <element name="product_class" type="{http://pds.nasa.gov/pds4/pds/v1}product_class"/>
 *         <element name="Alias_List" type="{http://pds.nasa.gov/pds4/pds/v1}Alias_List" minOccurs="0"/>
 *         <element name="Citation_Information" type="{http://pds.nasa.gov/pds4/pds/v1}Citation_Information" minOccurs="0"/>
 *         <element name="Modification_History" type="{http://pds.nasa.gov/pds4/pds/v1}Modification_History" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Identification_Area", propOrder = {
    "logicalIdentifier",
    "versionId",
    "title",
    "informationModelVersion",
    "productClass",
    "aliasList",
    "citationInformation",
    "modificationHistory"
})
public class IdentificationArea {

    @XmlElement(name = "logical_identifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String logicalIdentifier;
    @XmlElement(name = "version_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String versionId;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String title;
    @XmlElement(name = "information_model_version", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String informationModelVersion;
    @XmlElement(name = "product_class", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String productClass;
    @XmlElement(name = "Alias_List")
    protected AliasList aliasList;
    @XmlElement(name = "Citation_Information")
    protected CitationInformation citationInformation;
    @XmlElement(name = "Modification_History")
    protected ModificationHistory modificationHistory;

    /**
     * Gets the value of the logicalIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalIdentifier() {
        return logicalIdentifier;
    }

    /**
     * Sets the value of the logicalIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalIdentifier(String value) {
        this.logicalIdentifier = value;
    }

    /**
     * Gets the value of the versionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * Sets the value of the versionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionId(String value) {
        this.versionId = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the informationModelVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformationModelVersion() {
        return informationModelVersion;
    }

    /**
     * Sets the value of the informationModelVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformationModelVersion(String value) {
        this.informationModelVersion = value;
    }

    /**
     * Gets the value of the productClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductClass() {
        return productClass;
    }

    /**
     * Sets the value of the productClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductClass(String value) {
        this.productClass = value;
    }

    /**
     * Gets the value of the aliasList property.
     * 
     * @return
     *     possible object is
     *     {@link AliasList }
     *     
     */
    public AliasList getAliasList() {
        return aliasList;
    }

    /**
     * Sets the value of the aliasList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AliasList }
     *     
     */
    public void setAliasList(AliasList value) {
        this.aliasList = value;
    }

    /**
     * Gets the value of the citationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link CitationInformation }
     *     
     */
    public CitationInformation getCitationInformation() {
        return citationInformation;
    }

    /**
     * Sets the value of the citationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitationInformation }
     *     
     */
    public void setCitationInformation(CitationInformation value) {
        this.citationInformation = value;
    }

    /**
     * Gets the value of the modificationHistory property.
     * 
     * @return
     *     possible object is
     *     {@link ModificationHistory }
     *     
     */
    public ModificationHistory getModificationHistory() {
        return modificationHistory;
    }

    /**
     * Sets the value of the modificationHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationHistory }
     *     
     */
    public void setModificationHistory(ModificationHistory value) {
        this.modificationHistory = value;
    }

}
