//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Information_Package_Component class
 *         associates a Bundle, Collections or Basic Products with Checksum
 *         and Storage Manifests.
 * 
 * <p>Java class for Information_Package_Component complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Information_Package_Component">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="checksum_manifest_checksum" type="{http://pds.nasa.gov/pds4/pds/v1}checksum_manifest_checksum" minOccurs="0"/>
 *         <element name="checksum_type" type="{http://pds.nasa.gov/pds4/pds/v1}checksum_type" minOccurs="0"/>
 *         <element name="transfer_manifest_checksum" type="{http://pds.nasa.gov/pds4/pds/v1}transfer_manifest_checksum" minOccurs="0"/>
 *         <element ref="{http://pds.nasa.gov/pds4/pds/v1}Internal_Reference" maxOccurs="unbounded"/>
 *         <element name="File_Area_Checksum_Manifest" type="{http://pds.nasa.gov/pds4/pds/v1}File_Area_Checksum_Manifest" minOccurs="0"/>
 *         <element name="File_Area_Transfer_Manifest" type="{http://pds.nasa.gov/pds4/pds/v1}File_Area_Transfer_Manifest" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Information_Package_Component", propOrder = {
    "checksumManifestChecksum",
    "checksumType",
    "transferManifestChecksum",
    "internalReference",
    "fileAreaChecksumManifest",
    "fileAreaTransferManifest"
})
public class InformationPackageComponent {

    @XmlElement(name = "checksum_manifest_checksum")
    protected String checksumManifestChecksum;
    @XmlElement(name = "checksum_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String checksumType;
    @XmlElement(name = "transfer_manifest_checksum")
    protected String transferManifestChecksum;
    @XmlElement(name = "Internal_Reference", required = true)
    protected List<InternalReference> internalReference;
    @XmlElement(name = "File_Area_Checksum_Manifest")
    protected FileAreaChecksumManifest fileAreaChecksumManifest;
    @XmlElement(name = "File_Area_Transfer_Manifest")
    protected FileAreaTransferManifest fileAreaTransferManifest;

    /**
     * Gets the value of the checksumManifestChecksum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChecksumManifestChecksum() {
        return checksumManifestChecksum;
    }

    /**
     * Sets the value of the checksumManifestChecksum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChecksumManifestChecksum(String value) {
        this.checksumManifestChecksum = value;
    }

    /**
     * Gets the value of the checksumType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChecksumType() {
        return checksumType;
    }

    /**
     * Sets the value of the checksumType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChecksumType(String value) {
        this.checksumType = value;
    }

    /**
     * Gets the value of the transferManifestChecksum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferManifestChecksum() {
        return transferManifestChecksum;
    }

    /**
     * Sets the value of the transferManifestChecksum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferManifestChecksum(String value) {
        this.transferManifestChecksum = value;
    }

    /**
     * Gets the value of the internalReference property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internalReference property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getInternalReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InternalReference }
     * </p>
     * 
     * 
     * @return
     *     The value of the internalReference property.
     */
    public List<InternalReference> getInternalReference() {
        if (internalReference == null) {
            internalReference = new ArrayList<>();
        }
        return this.internalReference;
    }

    /**
     * Gets the value of the fileAreaChecksumManifest property.
     * 
     * @return
     *     possible object is
     *     {@link FileAreaChecksumManifest }
     *     
     */
    public FileAreaChecksumManifest getFileAreaChecksumManifest() {
        return fileAreaChecksumManifest;
    }

    /**
     * Sets the value of the fileAreaChecksumManifest property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileAreaChecksumManifest }
     *     
     */
    public void setFileAreaChecksumManifest(FileAreaChecksumManifest value) {
        this.fileAreaChecksumManifest = value;
    }

    /**
     * Gets the value of the fileAreaTransferManifest property.
     * 
     * @return
     *     possible object is
     *     {@link FileAreaTransferManifest }
     *     
     */
    public FileAreaTransferManifest getFileAreaTransferManifest() {
        return fileAreaTransferManifest;
    }

    /**
     * Sets the value of the fileAreaTransferManifest property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileAreaTransferManifest }
     *     
     */
    public void setFileAreaTransferManifest(FileAreaTransferManifest value) {
        this.fileAreaTransferManifest = value;
    }

}
