//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Instrument Host class provides a description
 *         of the phyiscal object upon which an instrument is mounted. This
 *         class captures the PDS3 catalog Instrument Host
 *         information.
 * 
 * <p>Java class for Instrument_Host_PDS3 complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Instrument_Host_PDS3">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="instrument_host_name" type="{http://pds.nasa.gov/pds4/pds/v1}instrument_host_name"/>
 *         <element name="instrument_host_desc" type="{http://pds.nasa.gov/pds4/pds/v1}instrument_host_desc"/>
 *         <element name="instrument_host_id" type="{http://pds.nasa.gov/pds4/pds/v1}instrument_host_id"/>
 *         <element name="instrument_host_type" type="{http://pds.nasa.gov/pds4/pds/v1}instrument_host_type"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Instrument_Host_PDS3", propOrder = {
    "instrumentHostName",
    "instrumentHostDesc",
    "instrumentHostId",
    "instrumentHostType"
})
public class InstrumentHostPDS3 {

    @XmlElement(name = "instrument_host_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String instrumentHostName;
    @XmlElement(name = "instrument_host_desc", required = true)
    protected String instrumentHostDesc;
    @XmlElement(name = "instrument_host_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String instrumentHostId;
    @XmlElement(name = "instrument_host_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String instrumentHostType;

    /**
     * Gets the value of the instrumentHostName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentHostName() {
        return instrumentHostName;
    }

    /**
     * Sets the value of the instrumentHostName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentHostName(String value) {
        this.instrumentHostName = value;
    }

    /**
     * Gets the value of the instrumentHostDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentHostDesc() {
        return instrumentHostDesc;
    }

    /**
     * Sets the value of the instrumentHostDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentHostDesc(String value) {
        this.instrumentHostDesc = value;
    }

    /**
     * Gets the value of the instrumentHostId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentHostId() {
        return instrumentHostId;
    }

    /**
     * Sets the value of the instrumentHostId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentHostId(String value) {
        this.instrumentHostId = value;
    }

    /**
     * Gets the value of the instrumentHostType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentHostType() {
        return instrumentHostType;
    }

    /**
     * Sets the value of the instrumentHostType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentHostType(String value) {
        this.instrumentHostType = value;
    }

}
