//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * The maximum_field_length attribute sets an
 *         upper, inclusive bound on the number of bytes in the
 *         field.
 * 
 * <p>Java class for maximum_field_length complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="maximum_field_length">
 *   <simpleContent>
 *     <extension base="<http://pds.nasa.gov/pds4/pds/v1>maximum_field_length_WO_Units">
 *       <attribute name="unit" use="required" type="{http://pds.nasa.gov/pds4/pds/v1}Units_of_Storage" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "maximum_field_length", propOrder = {
    "value"
})
public class MaximumFieldLength {

    @XmlValue
    protected BigInteger value;
    @XmlAttribute(name = "unit", required = true)
    protected UnitsOfStorage unit;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValue(BigInteger value) {
        this.value = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link UnitsOfStorage }
     *     
     */
    public UnitsOfStorage getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitsOfStorage }
     *     
     */
    public void setUnit(UnitsOfStorage value) {
        this.unit = value;
    }

}
