//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Object Statistics class provides a set of
 *         values that provide metrics about the object.
 * 
 * <p>Java class for Object_Statistics complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Object_Statistics">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="local_identifier" type="{http://pds.nasa.gov/pds4/pds/v1}local_identifier" minOccurs="0"/>
 *         <element name="maximum" type="{http://pds.nasa.gov/pds4/pds/v1}maximum" minOccurs="0"/>
 *         <element name="minimum" type="{http://pds.nasa.gov/pds4/pds/v1}minimum" minOccurs="0"/>
 *         <element name="mean" type="{http://pds.nasa.gov/pds4/pds/v1}mean" minOccurs="0"/>
 *         <element name="standard_deviation" type="{http://pds.nasa.gov/pds4/pds/v1}standard_deviation" minOccurs="0"/>
 *         <element name="bit_mask" type="{http://pds.nasa.gov/pds4/pds/v1}bit_mask" minOccurs="0"/>
 *         <element name="median" type="{http://pds.nasa.gov/pds4/pds/v1}median" minOccurs="0"/>
 *         <element name="md5_checksum" type="{http://pds.nasa.gov/pds4/pds/v1}md5_checksum" minOccurs="0"/>
 *         <element name="maximum_scaled_value" type="{http://pds.nasa.gov/pds4/pds/v1}maximum_scaled_value" minOccurs="0"/>
 *         <element name="minimum_scaled_value" type="{http://pds.nasa.gov/pds4/pds/v1}minimum_scaled_value" minOccurs="0"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Object_Statistics", propOrder = {
    "localIdentifier",
    "maximum",
    "minimum",
    "mean",
    "standardDeviation",
    "bitMask",
    "median",
    "md5Checksum",
    "maximumScaledValue",
    "minimumScaledValue",
    "description"
})
public class ObjectStatistics {

    @XmlElement(name = "local_identifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String localIdentifier;
    protected Double maximum;
    protected Double minimum;
    protected Double mean;
    @XmlElement(name = "standard_deviation")
    protected Double standardDeviation;
    @XmlElement(name = "bit_mask")
    protected String bitMask;
    protected Double median;
    @XmlElement(name = "md5_checksum")
    protected String md5Checksum;
    @XmlElement(name = "maximum_scaled_value")
    protected Double maximumScaledValue;
    @XmlElement(name = "minimum_scaled_value")
    protected Double minimumScaledValue;
    protected String description;

    /**
     * Gets the value of the localIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalIdentifier() {
        return localIdentifier;
    }

    /**
     * Sets the value of the localIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalIdentifier(String value) {
        this.localIdentifier = value;
    }

    /**
     * Gets the value of the maximum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaximum() {
        return maximum;
    }

    /**
     * Sets the value of the maximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaximum(Double value) {
        this.maximum = value;
    }

    /**
     * Gets the value of the minimum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinimum() {
        return minimum;
    }

    /**
     * Sets the value of the minimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinimum(Double value) {
        this.minimum = value;
    }

    /**
     * Gets the value of the mean property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMean() {
        return mean;
    }

    /**
     * Sets the value of the mean property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMean(Double value) {
        this.mean = value;
    }

    /**
     * Gets the value of the standardDeviation property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getStandardDeviation() {
        return standardDeviation;
    }

    /**
     * Sets the value of the standardDeviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStandardDeviation(Double value) {
        this.standardDeviation = value;
    }

    /**
     * Gets the value of the bitMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBitMask() {
        return bitMask;
    }

    /**
     * Sets the value of the bitMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBitMask(String value) {
        this.bitMask = value;
    }

    /**
     * Gets the value of the median property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMedian() {
        return median;
    }

    /**
     * Sets the value of the median property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMedian(Double value) {
        this.median = value;
    }

    /**
     * Gets the value of the md5Checksum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMd5Checksum() {
        return md5Checksum;
    }

    /**
     * Sets the value of the md5Checksum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMd5Checksum(String value) {
        this.md5Checksum = value;
    }

    /**
     * Gets the value of the maximumScaledValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaximumScaledValue() {
        return maximumScaledValue;
    }

    /**
     * Sets the value of the maximumScaledValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaximumScaledValue(Double value) {
        this.maximumScaledValue = value;
    }

    /**
     * Gets the value of the minimumScaledValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinimumScaledValue() {
        return minimumScaledValue;
    }

    /**
     * Sets the value of the minimumScaledValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinimumScaledValue(Double value) {
        this.minimumScaledValue = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
