//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Observing System Component class references
 *         one or more subsystems used to collect data. A subsystem can be
 *         an instrument_host, instrument, or any other similar product.
 *         Each subsystem is categorized as either a sensor or a source. If
 *         the observing system includes both a sensor and a source,
 *         Observing System Component occurs twice (once for each type)
 *         otherwise it only occurs once.
 * 
 * <p>Java class for Observing_System_Component complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Observing_System_Component">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name" type="{http://pds.nasa.gov/pds4/pds/v1}name"/>
 *         <element name="type" type="{http://pds.nasa.gov/pds4/pds/v1}type"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description" minOccurs="0"/>
 *         <element ref="{http://pds.nasa.gov/pds4/pds/v1}Internal_Reference" minOccurs="0"/>
 *         <element ref="{http://pds.nasa.gov/pds4/pds/v1}External_Reference" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Observing_System_Component", propOrder = {
    "name",
    "type",
    "description",
    "internalReference",
    "externalReference"
})
public class ObservingSystemComponent {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String type;
    protected String description;
    @XmlElement(name = "Internal_Reference")
    protected InternalReference internalReference;
    @XmlElement(name = "External_Reference")
    protected List<ExternalReference> externalReference;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the internalReference property.
     * 
     * @return
     *     possible object is
     *     {@link InternalReference }
     *     
     */
    public InternalReference getInternalReference() {
        return internalReference;
    }

    /**
     * Sets the value of the internalReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalReference }
     *     
     */
    public void setInternalReference(InternalReference value) {
        this.internalReference = value;
    }

    /**
     * Gets the value of the externalReference property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalReference property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExternalReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalReference }
     * </p>
     * 
     * 
     * @return
     *     The value of the externalReference property.
     */
    public List<ExternalReference> getExternalReference() {
        if (externalReference == null) {
            externalReference = new ArrayList<>();
        }
        return this.externalReference;
    }

}
