//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The observation area consists of attributes that
 *         provide information about the circumstances under which the data
 *         were collected.
 * 
 * <p>Java class for Observation_Area complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Observation_Area">
 *   <complexContent>
 *     <restriction base="{http://pds.nasa.gov/pds4/pds/v1}Context_Area">
 *       <sequence>
 *         <element name="comment" type="{http://pds.nasa.gov/pds4/pds/v1}comment" minOccurs="0"/>
 *         <element name="Time_Coordinates" type="{http://pds.nasa.gov/pds4/pds/v1}Time_Coordinates"/>
 *         <element name="Primary_Result_Summary" type="{http://pds.nasa.gov/pds4/pds/v1}Primary_Result_Summary" minOccurs="0"/>
 *         <element name="Investigation_Area" type="{http://pds.nasa.gov/pds4/pds/v1}Investigation_Area" maxOccurs="unbounded"/>
 *         <element name="Observing_System" type="{http://pds.nasa.gov/pds4/pds/v1}Observing_System" maxOccurs="unbounded"/>
 *         <element name="Target_Identification" type="{http://pds.nasa.gov/pds4/pds/v1}Target_Identification" maxOccurs="unbounded"/>
 *         <element name="Mission_Area" type="{http://pds.nasa.gov/pds4/pds/v1}Mission_Area" minOccurs="0"/>
 *         <element name="Discipline_Area" type="{http://pds.nasa.gov/pds4/pds/v1}Discipline_Area" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Observation_Area")
public class ObservationArea
    extends ContextArea
{


}
