//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The PDS Affiliate class provides a description
 *         of a person who has an association with the planetary science
 *         community and has access to PDS resources not normally allowed
 *         to the general public.
 * 
 * <p>Java class for PDS_Affiliate complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="PDS_Affiliate">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="name" type="{http://pds.nasa.gov/pds4/pds/v1}name" minOccurs="0"/>
 *         <element name="registration_date" type="{http://pds.nasa.gov/pds4/pds/v1}registration_date"/>
 *         <element name="electronic_mail_address" type="{http://pds.nasa.gov/pds4/pds/v1}electronic_mail_address" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="sort_name" type="{http://pds.nasa.gov/pds4/pds/v1}sort_name"/>
 *         <element name="affiliation_type" type="{http://pds.nasa.gov/pds4/pds/v1}affiliation_type"/>
 *         <element name="alternate_telephone_number" type="{http://pds.nasa.gov/pds4/pds/v1}alternate_telephone_number" minOccurs="0"/>
 *         <element name="institution_name" type="{http://pds.nasa.gov/pds4/pds/v1}institution_name"/>
 *         <element name="phone_book_flag" type="{http://pds.nasa.gov/pds4/pds/v1}phone_book_flag"/>
 *         <element name="postal_address_text" type="{http://pds.nasa.gov/pds4/pds/v1}postal_address_text"/>
 *         <element name="team_name" type="{http://pds.nasa.gov/pds4/pds/v1}team_name" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="telephone_number" type="{http://pds.nasa.gov/pds4/pds/v1}telephone_number" minOccurs="0"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PDS_Affiliate", propOrder = {
    "name",
    "registrationDate",
    "electronicMailAddress",
    "sortName",
    "affiliationType",
    "alternateTelephoneNumber",
    "institutionName",
    "phoneBookFlag",
    "postalAddressText",
    "teamName",
    "telephoneNumber",
    "description"
})
public class PDSAffiliate {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;
    @XmlElement(name = "registration_date", required = true)
    protected String registrationDate;
    @XmlElement(name = "electronic_mail_address")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> electronicMailAddress;
    @XmlElement(name = "sort_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String sortName;
    @XmlElement(name = "affiliation_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String affiliationType;
    @XmlElement(name = "alternate_telephone_number")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String alternateTelephoneNumber;
    @XmlElement(name = "institution_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String institutionName;
    @XmlElement(name = "phone_book_flag")
    protected boolean phoneBookFlag;
    @XmlElement(name = "postal_address_text", required = true)
    protected String postalAddressText;
    @XmlElement(name = "team_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> teamName;
    @XmlElement(name = "telephone_number")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String telephoneNumber;
    @XmlElement(required = true)
    protected String description;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the registrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Sets the value of the registrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationDate(String value) {
        this.registrationDate = value;
    }

    /**
     * Gets the value of the electronicMailAddress property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the electronicMailAddress property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getElectronicMailAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the electronicMailAddress property.
     */
    public List<String> getElectronicMailAddress() {
        if (electronicMailAddress == null) {
            electronicMailAddress = new ArrayList<>();
        }
        return this.electronicMailAddress;
    }

    /**
     * Gets the value of the sortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortName() {
        return sortName;
    }

    /**
     * Sets the value of the sortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortName(String value) {
        this.sortName = value;
    }

    /**
     * Gets the value of the affiliationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliationType() {
        return affiliationType;
    }

    /**
     * Sets the value of the affiliationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliationType(String value) {
        this.affiliationType = value;
    }

    /**
     * Gets the value of the alternateTelephoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateTelephoneNumber() {
        return alternateTelephoneNumber;
    }

    /**
     * Sets the value of the alternateTelephoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateTelephoneNumber(String value) {
        this.alternateTelephoneNumber = value;
    }

    /**
     * Gets the value of the institutionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstitutionName() {
        return institutionName;
    }

    /**
     * Sets the value of the institutionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstitutionName(String value) {
        this.institutionName = value;
    }

    /**
     * Gets the value of the phoneBookFlag property.
     * 
     */
    public boolean isPhoneBookFlag() {
        return phoneBookFlag;
    }

    /**
     * Sets the value of the phoneBookFlag property.
     * 
     */
    public void setPhoneBookFlag(boolean value) {
        this.phoneBookFlag = value;
    }

    /**
     * Gets the value of the postalAddressText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalAddressText() {
        return postalAddressText;
    }

    /**
     * Sets the value of the postalAddressText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalAddressText(String value) {
        this.postalAddressText = value;
    }

    /**
     * Gets the value of the teamName property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the teamName property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTeamName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the teamName property.
     */
    public List<String> getTeamName() {
        if (teamName == null) {
            teamName = new ArrayList<>();
        }
        return this.teamName;
    }

    /**
     * Gets the value of the telephoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * Sets the value of the telephoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneNumber(String value) {
        this.telephoneNumber = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
