//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A target product describes a target. This
 *         product captures a reduced set of the PDS3 catalog target
 *         information.
 * 
 * <p>Java class for Product_Target_PDS3 complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Product_Target_PDS3">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Product">
 *       <sequence>
 *         <element name="Reference_List" type="{http://pds.nasa.gov/pds4/pds/v1}Reference_List" minOccurs="0"/>
 *         <element name="Target_PDS3" type="{http://pds.nasa.gov/pds4/pds/v1}Target_PDS3"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product_Target_PDS3", propOrder = {
    "referenceList",
    "targetPDS3"
})
public class ProductTargetPDS3
    extends Product
{

    @XmlElement(name = "Reference_List")
    protected ReferenceList referenceList;
    @XmlElement(name = "Target_PDS3", required = true)
    protected TargetPDS3 targetPDS3;

    /**
     * Gets the value of the referenceList property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceList }
     *     
     */
    public ReferenceList getReferenceList() {
        return referenceList;
    }

    /**
     * Sets the value of the referenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceList }
     *     
     */
    public void setReferenceList(ReferenceList value) {
        this.referenceList = value;
    }

    /**
     * Gets the value of the targetPDS3 property.
     * 
     * @return
     *     possible object is
     *     {@link TargetPDS3 }
     *     
     */
    public TargetPDS3 getTargetPDS3() {
        return targetPDS3;
    }

    /**
     * Sets the value of the targetPDS3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetPDS3 }
     *     
     */
    public void setTargetPDS3(TargetPDS3 value) {
        this.targetPDS3 = value;
    }

}
