//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Product Thumbnail class defines a product
 *         consisting of one encoded byte stream digital
 *         object.
 * 
 * <p>Java class for Product_Thumbnail complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Product_Thumbnail">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Product">
 *       <sequence>
 *         <element name="Reference_List" type="{http://pds.nasa.gov/pds4/pds/v1}Reference_List" minOccurs="0"/>
 *         <element name="File_Area_Encoded_Image" type="{http://pds.nasa.gov/pds4/pds/v1}File_Area_Encoded_Image"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product_Thumbnail", propOrder = {
    "referenceList",
    "fileAreaEncodedImage"
})
public class ProductThumbnail
    extends Product
{

    @XmlElement(name = "Reference_List")
    protected ReferenceList referenceList;
    @XmlElement(name = "File_Area_Encoded_Image", required = true)
    protected FileAreaEncodedImage fileAreaEncodedImage;

    /**
     * Gets the value of the referenceList property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceList }
     *     
     */
    public ReferenceList getReferenceList() {
        return referenceList;
    }

    /**
     * Sets the value of the referenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceList }
     *     
     */
    public void setReferenceList(ReferenceList value) {
        this.referenceList = value;
    }

    /**
     * Gets the value of the fileAreaEncodedImage property.
     * 
     * @return
     *     possible object is
     *     {@link FileAreaEncodedImage }
     *     
     */
    public FileAreaEncodedImage getFileAreaEncodedImage() {
        return fileAreaEncodedImage;
    }

    /**
     * Sets the value of the fileAreaEncodedImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileAreaEncodedImage }
     *     
     */
    public void setFileAreaEncodedImage(FileAreaEncodedImage value) {
        this.fileAreaEncodedImage = value;
    }

}
