//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A Product_Observational is a set of one or more
 *         information objects produced by an observing
 *         system.
 * 
 * <p>Java class for Product_Observational complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Product_Observational">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Product">
 *       <sequence>
 *         <element name="Observation_Area" type="{http://pds.nasa.gov/pds4/pds/v1}Observation_Area"/>
 *         <element name="Reference_List" type="{http://pds.nasa.gov/pds4/pds/v1}Reference_List" minOccurs="0"/>
 *         <element name="File_Area_Observational" type="{http://pds.nasa.gov/pds4/pds/v1}File_Area_Observational" maxOccurs="unbounded"/>
 *         <element name="File_Area_Observational_Supplemental" type="{http://pds.nasa.gov/pds4/pds/v1}File_Area_Observational_Supplemental" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product_Observational", propOrder = {
    "observationArea",
    "referenceList",
    "fileAreaObservational",
    "fileAreaObservationalSupplemental"
})
public class ProductObservational
    extends Product
{

    @XmlElement(name = "Observation_Area", required = true)
    protected ObservationArea observationArea;
    @XmlElement(name = "Reference_List")
    protected ReferenceList referenceList;
    @XmlElement(name = "File_Area_Observational", required = true)
    protected List<FileAreaObservational> fileAreaObservational;
    @XmlElement(name = "File_Area_Observational_Supplemental")
    protected List<FileAreaObservationalSupplemental> fileAreaObservationalSupplemental;

    /**
     * Gets the value of the observationArea property.
     * 
     * @return
     *     possible object is
     *     {@link ObservationArea }
     *     
     */
    public ObservationArea getObservationArea() {
        return observationArea;
    }

    /**
     * Sets the value of the observationArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservationArea }
     *     
     */
    public void setObservationArea(ObservationArea value) {
        this.observationArea = value;
    }

    /**
     * Gets the value of the referenceList property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceList }
     *     
     */
    public ReferenceList getReferenceList() {
        return referenceList;
    }

    /**
     * Sets the value of the referenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceList }
     *     
     */
    public void setReferenceList(ReferenceList value) {
        this.referenceList = value;
    }

    /**
     * Gets the value of the fileAreaObservational property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileAreaObservational property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getFileAreaObservational().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileAreaObservational }
     * </p>
     * 
     * 
     * @return
     *     The value of the fileAreaObservational property.
     */
    public List<FileAreaObservational> getFileAreaObservational() {
        if (fileAreaObservational == null) {
            fileAreaObservational = new ArrayList<>();
        }
        return this.fileAreaObservational;
    }

    /**
     * Gets the value of the fileAreaObservationalSupplemental property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileAreaObservationalSupplemental property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getFileAreaObservationalSupplemental().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileAreaObservationalSupplemental }
     * </p>
     * 
     * 
     * @return
     *     The value of the fileAreaObservationalSupplemental property.
     */
    public List<FileAreaObservationalSupplemental> getFileAreaObservationalSupplemental() {
        if (fileAreaObservationalSupplemental == null) {
            fileAreaObservationalSupplemental = new ArrayList<>();
        }
        return this.fileAreaObservationalSupplemental;
    }

}
