//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Data Set PDS3 product  is used to create
 *         proxy labels for the data sets in the PDS3 Data Set
 *         catalog.
 * 
 * <p>Java class for Product_Data_Set_PDS3 complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Product_Data_Set_PDS3">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Product">
 *       <sequence>
 *         <element name="Reference_List" type="{http://pds.nasa.gov/pds4/pds/v1}Reference_List" minOccurs="0"/>
 *         <element name="Data_Set_PDS3" type="{http://pds.nasa.gov/pds4/pds/v1}Data_Set_PDS3"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product_Data_Set_PDS3", propOrder = {
    "referenceList",
    "dataSetPDS3"
})
public class ProductDataSetPDS3
    extends Product
{

    @XmlElement(name = "Reference_List")
    protected ReferenceList referenceList;
    @XmlElement(name = "Data_Set_PDS3", required = true)
    protected DataSetPDS3 dataSetPDS3;

    /**
     * Gets the value of the referenceList property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceList }
     *     
     */
    public ReferenceList getReferenceList() {
        return referenceList;
    }

    /**
     * Sets the value of the referenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceList }
     *     
     */
    public void setReferenceList(ReferenceList value) {
        this.referenceList = value;
    }

    /**
     * Gets the value of the dataSetPDS3 property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetPDS3 }
     *     
     */
    public DataSetPDS3 getDataSetPDS3() {
        return dataSetPDS3;
    }

    /**
     * Sets the value of the dataSetPDS3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetPDS3 }
     *     
     */
    public void setDataSetPDS3(DataSetPDS3 value) {
        this.dataSetPDS3 = value;
    }

}
