//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Product SIP Deep Archive class defines a
 *         Submission Information Package (SIP) for the NASA planetary
 *         science deep archive.
 * 
 * <p>Java class for Product_SIP_Deep_Archive complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Product_SIP_Deep_Archive">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Product">
 *       <sequence>
 *         <element name="Information_Package_Component_Deep_Archive" type="{http://pds.nasa.gov/pds4/pds/v1}Information_Package_Component_Deep_Archive"/>
 *         <element name="SIP_Deep_Archive" type="{http://pds.nasa.gov/pds4/pds/v1}SIP_Deep_Archive"/>
 *         <element name="Reference_List" type="{http://pds.nasa.gov/pds4/pds/v1}Reference_List" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product_SIP_Deep_Archive", propOrder = {
    "informationPackageComponentDeepArchive",
    "sipDeepArchive",
    "referenceList"
})
public class ProductSIPDeepArchive
    extends Product
{

    @XmlElement(name = "Information_Package_Component_Deep_Archive", required = true)
    protected InformationPackageComponentDeepArchive informationPackageComponentDeepArchive;
    @XmlElement(name = "SIP_Deep_Archive", required = true)
    protected SIPDeepArchive sipDeepArchive;
    @XmlElement(name = "Reference_List")
    protected ReferenceList referenceList;

    /**
     * Gets the value of the informationPackageComponentDeepArchive property.
     * 
     * @return
     *     possible object is
     *     {@link InformationPackageComponentDeepArchive }
     *     
     */
    public InformationPackageComponentDeepArchive getInformationPackageComponentDeepArchive() {
        return informationPackageComponentDeepArchive;
    }

    /**
     * Sets the value of the informationPackageComponentDeepArchive property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformationPackageComponentDeepArchive }
     *     
     */
    public void setInformationPackageComponentDeepArchive(InformationPackageComponentDeepArchive value) {
        this.informationPackageComponentDeepArchive = value;
    }

    /**
     * Gets the value of the sipDeepArchive property.
     * 
     * @return
     *     possible object is
     *     {@link SIPDeepArchive }
     *     
     */
    public SIPDeepArchive getSIPDeepArchive() {
        return sipDeepArchive;
    }

    /**
     * Sets the value of the sipDeepArchive property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIPDeepArchive }
     *     
     */
    public void setSIPDeepArchive(SIPDeepArchive value) {
        this.sipDeepArchive = value;
    }

    /**
     * Gets the value of the referenceList property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceList }
     *     
     */
    public ReferenceList getReferenceList() {
        return referenceList;
    }

    /**
     * Sets the value of the referenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceList }
     *     
     */
    public void setReferenceList(ReferenceList value) {
        this.referenceList = value;
    }

}
