//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Product File Repository class consists of a
 *         single text file. This product is used to register a file in a
 *         repository.
 * 
 * <p>Java class for Product_File_Repository complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Product_File_Repository">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Product">
 *       <sequence>
 *         <element name="Reference_List" type="{http://pds.nasa.gov/pds4/pds/v1}Reference_List" minOccurs="0"/>
 *         <element name="File_Area_Binary" type="{http://pds.nasa.gov/pds4/pds/v1}File_Area_Binary"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product_File_Repository", propOrder = {
    "referenceList",
    "fileAreaBinary"
})
public class ProductFileRepository
    extends Product
{

    @XmlElement(name = "Reference_List")
    protected ReferenceList referenceList;
    @XmlElement(name = "File_Area_Binary", required = true)
    protected FileAreaBinary fileAreaBinary;

    /**
     * Gets the value of the referenceList property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceList }
     *     
     */
    public ReferenceList getReferenceList() {
        return referenceList;
    }

    /**
     * Sets the value of the referenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceList }
     *     
     */
    public void setReferenceList(ReferenceList value) {
        this.referenceList = value;
    }

    /**
     * Gets the value of the fileAreaBinary property.
     * 
     * @return
     *     possible object is
     *     {@link FileAreaBinary }
     *     
     */
    public FileAreaBinary getFileAreaBinary() {
        return fileAreaBinary;
    }

    /**
     * Sets the value of the fileAreaBinary property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileAreaBinary }
     *     
     */
    public void setFileAreaBinary(FileAreaBinary value) {
        this.fileAreaBinary = value;
    }

}
