//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An Mission product describes a mission. This
 *         product captures the PDS3 catalog mission
 *         information.
 * 
 * <p>Java class for Product_Mission_PDS3 complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Product_Mission_PDS3">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Product">
 *       <sequence>
 *         <element name="Reference_List" type="{http://pds.nasa.gov/pds4/pds/v1}Reference_List" minOccurs="0"/>
 *         <element name="Mission_PDS3" type="{http://pds.nasa.gov/pds4/pds/v1}Mission_PDS3"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product_Mission_PDS3", propOrder = {
    "referenceList",
    "missionPDS3"
})
public class ProductMissionPDS3
    extends Product
{

    @XmlElement(name = "Reference_List")
    protected ReferenceList referenceList;
    @XmlElement(name = "Mission_PDS3", required = true)
    protected MissionPDS3 missionPDS3;

    /**
     * Gets the value of the referenceList property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceList }
     *     
     */
    public ReferenceList getReferenceList() {
        return referenceList;
    }

    /**
     * Sets the value of the referenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceList }
     *     
     */
    public void setReferenceList(ReferenceList value) {
        this.referenceList = value;
    }

    /**
     * Gets the value of the missionPDS3 property.
     * 
     * @return
     *     possible object is
     *     {@link MissionPDS3 }
     *     
     */
    public MissionPDS3 getMissionPDS3() {
        return missionPDS3;
    }

    /**
     * Sets the value of the missionPDS3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MissionPDS3 }
     *     
     */
    public void setMissionPDS3(MissionPDS3 value) {
        this.missionPDS3 = value;
    }

}
