//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Property Map class defines a table
 *         consisting of a set of data elements and their values. The data
 *         elements in this table are considered to be locally defined and
 *         not subject to standards except for nomenclature
 *         rules.
 * 
 * <p>Java class for Property_Map complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Property_Map">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="identifier" type="{http://pds.nasa.gov/pds4/pds/v1}identifier" minOccurs="0"/>
 *         <element name="title" type="{http://pds.nasa.gov/pds4/pds/v1}title" minOccurs="0"/>
 *         <element name="model_object_id" type="{http://pds.nasa.gov/pds4/pds/v1}model_object_id"/>
 *         <element name="model_object_type" type="{http://pds.nasa.gov/pds4/pds/v1}model_object_type"/>
 *         <element name="instance_id" type="{http://pds.nasa.gov/pds4/pds/v1}instance_id" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="external_namespace_id" type="{http://pds.nasa.gov/pds4/pds/v1}external_namespace_id" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description" minOccurs="0"/>
 *         <element name="Property_Map_Entry" type="{http://pds.nasa.gov/pds4/pds/v1}Property_Map_Entry" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Property_Map", propOrder = {
    "identifier",
    "title",
    "modelObjectId",
    "modelObjectType",
    "instanceId",
    "externalNamespaceId",
    "description",
    "propertyMapEntry"
})
public class PropertyMap {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String identifier;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String title;
    @XmlElement(name = "model_object_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String modelObjectId;
    @XmlElement(name = "model_object_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String modelObjectType;
    @XmlElement(name = "instance_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> instanceId;
    @XmlElement(name = "external_namespace_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> externalNamespaceId;
    protected String description;
    @XmlElement(name = "Property_Map_Entry", required = true)
    protected List<PropertyMapEntry> propertyMapEntry;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the modelObjectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelObjectId() {
        return modelObjectId;
    }

    /**
     * Sets the value of the modelObjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelObjectId(String value) {
        this.modelObjectId = value;
    }

    /**
     * Gets the value of the modelObjectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelObjectType() {
        return modelObjectType;
    }

    /**
     * Sets the value of the modelObjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelObjectType(String value) {
        this.modelObjectType = value;
    }

    /**
     * Gets the value of the instanceId property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instanceId property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getInstanceId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the instanceId property.
     */
    public List<String> getInstanceId() {
        if (instanceId == null) {
            instanceId = new ArrayList<>();
        }
        return this.instanceId;
    }

    /**
     * Gets the value of the externalNamespaceId property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalNamespaceId property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExternalNamespaceId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the externalNamespaceId property.
     */
    public List<String> getExternalNamespaceId() {
        if (externalNamespaceId == null) {
            externalNamespaceId = new ArrayList<>();
        }
        return this.externalNamespaceId;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the propertyMapEntry property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyMapEntry property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getPropertyMapEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyMapEntry }
     * </p>
     * 
     * 
     * @return
     *     The value of the propertyMapEntry property.
     */
    public List<PropertyMapEntry> getPropertyMapEntry() {
        if (propertyMapEntry == null) {
            propertyMapEntry = new ArrayList<>();
        }
        return this.propertyMapEntry;
    }

}
