//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Record_Delimited class is a component of the
 *         delimited table (spreadsheet) class and defines a record of the
 *         delimited table.
 * 
 * <p>Java class for Record_Delimited complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Record_Delimited">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Record">
 *       <sequence>
 *         <element name="maximum_record_length" type="{http://pds.nasa.gov/pds4/pds/v1}maximum_record_length" minOccurs="0"/>
 *         <choice maxOccurs="unbounded">
 *           <element name="Field_Delimited" type="{http://pds.nasa.gov/pds4/pds/v1}Field_Delimited"/>
 *           <element name="Group_Field_Delimited" type="{http://pds.nasa.gov/pds4/pds/v1}Group_Field_Delimited"/>
 *         </choice>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Record_Delimited", propOrder = {
    "maximumRecordLength",
    "fieldDelimitedOrGroupFieldDelimited"
})
public class RecordDelimited
    extends Record
{

    @XmlElement(name = "maximum_record_length")
    protected MaximumRecordLength maximumRecordLength;
    @XmlElements({
        @XmlElement(name = "Field_Delimited", type = FieldDelimited.class),
        @XmlElement(name = "Group_Field_Delimited", type = GroupFieldDelimited.class)
    })
    protected List<Object> fieldDelimitedOrGroupFieldDelimited;

    /**
     * Gets the value of the maximumRecordLength property.
     * 
     * @return
     *     possible object is
     *     {@link MaximumRecordLength }
     *     
     */
    public MaximumRecordLength getMaximumRecordLength() {
        return maximumRecordLength;
    }

    /**
     * Sets the value of the maximumRecordLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaximumRecordLength }
     *     
     */
    public void setMaximumRecordLength(MaximumRecordLength value) {
        this.maximumRecordLength = value;
    }

    /**
     * Gets the value of the fieldDelimitedOrGroupFieldDelimited property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldDelimitedOrGroupFieldDelimited property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getFieldDelimitedOrGroupFieldDelimited().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldDelimited }
     * {@link GroupFieldDelimited }
     * </p>
     * 
     * 
     * @return
     *     The value of the fieldDelimitedOrGroupFieldDelimited property.
     */
    public List<Object> getFieldDelimitedOrGroupFieldDelimited() {
        if (fieldDelimitedOrGroupFieldDelimited == null) {
            fieldDelimitedOrGroupFieldDelimited = new ArrayList<>();
        }
        return this.fieldDelimitedOrGroupFieldDelimited;
    }

}
