//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Service Description class defines a file
 *         that contains a standardized service
 *         specification.
 * 
 * <p>Java class for Service_Description complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Service_Description">
 *   <complexContent>
 *     <restriction base="{http://pds.nasa.gov/pds4/pds/v1}Parsable_Byte_Stream">
 *       <sequence>
 *         <element name="name" type="{http://pds.nasa.gov/pds4/pds/v1}name" minOccurs="0"/>
 *         <element name="local_identifier" type="{http://pds.nasa.gov/pds4/pds/v1}local_identifier" minOccurs="0"/>
 *         <element name="md5_checksum" type="{http://pds.nasa.gov/pds4/pds/v1}md5_checksum" minOccurs="0"/>
 *         <element name="offset" type="{http://pds.nasa.gov/pds4/pds/v1}offset"/>
 *         <element name="object_length" type="{http://pds.nasa.gov/pds4/pds/v1}object_length" minOccurs="0"/>
 *         <element name="parsing_standard_id" type="{http://pds.nasa.gov/pds4/pds/v1}parsing_standard_id"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Service_Description")
public class ServiceDescription
    extends ParsableByteStream
{


}
