//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Software Script class provides a description
 *         of a software code that is stored as a script.
 * 
 * <p>Java class for Software_Script complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Software_Script">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="files" type="{http://pds.nasa.gov/pds4/pds/v1}files"/>
 *         <element name="install_note" type="{http://pds.nasa.gov/pds4/pds/v1}install_note"/>
 *         <element name="supported_environment_note" type="{http://pds.nasa.gov/pds4/pds/v1}supported_environment_note"/>
 *         <element name="system_requirements_note" type="{http://pds.nasa.gov/pds4/pds/v1}system_requirements_note"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Software_Script", propOrder = {
    "files",
    "installNote",
    "supportedEnvironmentNote",
    "systemRequirementsNote"
})
public class SoftwareScript {

    @XmlElement(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger files;
    @XmlElement(name = "install_note", required = true)
    protected String installNote;
    @XmlElement(name = "supported_environment_note", required = true)
    protected String supportedEnvironmentNote;
    @XmlElement(name = "system_requirements_note", required = true)
    protected String systemRequirementsNote;

    /**
     * Gets the value of the files property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFiles() {
        return files;
    }

    /**
     * Sets the value of the files property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFiles(BigInteger value) {
        this.files = value;
    }

    /**
     * Gets the value of the installNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallNote() {
        return installNote;
    }

    /**
     * Sets the value of the installNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallNote(String value) {
        this.installNote = value;
    }

    /**
     * Gets the value of the supportedEnvironmentNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportedEnvironmentNote() {
        return supportedEnvironmentNote;
    }

    /**
     * Sets the value of the supportedEnvironmentNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportedEnvironmentNote(String value) {
        this.supportedEnvironmentNote = value;
    }

    /**
     * Gets the value of the systemRequirementsNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemRequirementsNote() {
        return systemRequirementsNote;
    }

    /**
     * Sets the value of the systemRequirementsNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemRequirementsNote(String value) {
        this.systemRequirementsNote = value;
    }

}
