//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Software Source class provides a description
 *         of a software code that is stored as source
 *         code.
 * 
 * <p>Java class for Software_Source complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Software_Source">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="compile_note" type="{http://pds.nasa.gov/pds4/pds/v1}compile_note"/>
 *         <element name="files" type="{http://pds.nasa.gov/pds4/pds/v1}files"/>
 *         <element name="os_version" type="{http://pds.nasa.gov/pds4/pds/v1}os_version"/>
 *         <element name="program_notes_id" type="{http://pds.nasa.gov/pds4/pds/v1}program_notes_id"/>
 *         <element name="software_dialect" type="{http://pds.nasa.gov/pds4/pds/v1}software_dialect"/>
 *         <element name="software_format_type" type="{http://pds.nasa.gov/pds4/pds/v1}software_format_type"/>
 *         <element name="software_language" type="{http://pds.nasa.gov/pds4/pds/v1}software_language"/>
 *         <element name="supported_architecture_note" type="{http://pds.nasa.gov/pds4/pds/v1}supported_architecture_note" maxOccurs="unbounded"/>
 *         <element name="supported_operating_system_note" type="{http://pds.nasa.gov/pds4/pds/v1}supported_operating_system_note" maxOccurs="unbounded"/>
 *         <element name="system_requirements_note" type="{http://pds.nasa.gov/pds4/pds/v1}system_requirements_note"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Software_Source", propOrder = {
    "compileNote",
    "files",
    "osVersion",
    "programNotesId",
    "softwareDialect",
    "softwareFormatType",
    "softwareLanguage",
    "supportedArchitectureNote",
    "supportedOperatingSystemNote",
    "systemRequirementsNote"
})
public class SoftwareSource {

    @XmlElement(name = "compile_note", required = true)
    protected String compileNote;
    @XmlElement(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger files;
    @XmlElement(name = "os_version", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String osVersion;
    @XmlElement(name = "program_notes_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String programNotesId;
    @XmlElement(name = "software_dialect", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String softwareDialect;
    @XmlElement(name = "software_format_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String softwareFormatType;
    @XmlElement(name = "software_language", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String softwareLanguage;
    @XmlElement(name = "supported_architecture_note", required = true)
    protected List<String> supportedArchitectureNote;
    @XmlElement(name = "supported_operating_system_note", required = true)
    protected List<String> supportedOperatingSystemNote;
    @XmlElement(name = "system_requirements_note", required = true)
    protected String systemRequirementsNote;

    /**
     * Gets the value of the compileNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompileNote() {
        return compileNote;
    }

    /**
     * Sets the value of the compileNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompileNote(String value) {
        this.compileNote = value;
    }

    /**
     * Gets the value of the files property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFiles() {
        return files;
    }

    /**
     * Sets the value of the files property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFiles(BigInteger value) {
        this.files = value;
    }

    /**
     * Gets the value of the osVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * Sets the value of the osVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsVersion(String value) {
        this.osVersion = value;
    }

    /**
     * Gets the value of the programNotesId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramNotesId() {
        return programNotesId;
    }

    /**
     * Sets the value of the programNotesId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramNotesId(String value) {
        this.programNotesId = value;
    }

    /**
     * Gets the value of the softwareDialect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareDialect() {
        return softwareDialect;
    }

    /**
     * Sets the value of the softwareDialect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareDialect(String value) {
        this.softwareDialect = value;
    }

    /**
     * Gets the value of the softwareFormatType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareFormatType() {
        return softwareFormatType;
    }

    /**
     * Sets the value of the softwareFormatType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareFormatType(String value) {
        this.softwareFormatType = value;
    }

    /**
     * Gets the value of the softwareLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareLanguage() {
        return softwareLanguage;
    }

    /**
     * Sets the value of the softwareLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareLanguage(String value) {
        this.softwareLanguage = value;
    }

    /**
     * Gets the value of the supportedArchitectureNote property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedArchitectureNote property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getSupportedArchitectureNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the supportedArchitectureNote property.
     */
    public List<String> getSupportedArchitectureNote() {
        if (supportedArchitectureNote == null) {
            supportedArchitectureNote = new ArrayList<>();
        }
        return this.supportedArchitectureNote;
    }

    /**
     * Gets the value of the supportedOperatingSystemNote property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedOperatingSystemNote property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getSupportedOperatingSystemNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the supportedOperatingSystemNote property.
     */
    public List<String> getSupportedOperatingSystemNote() {
        if (supportedOperatingSystemNote == null) {
            supportedOperatingSystemNote = new ArrayList<>();
        }
        return this.supportedOperatingSystemNote;
    }

    /**
     * Gets the value of the systemRequirementsNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemRequirementsNote() {
        return systemRequirementsNote;
    }

    /**
     * Sets the value of the systemRequirementsNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemRequirementsNote(String value) {
        this.systemRequirementsNote = value;
    }

}
