//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The SPICE Kernel class describes a SPICE
 *         object.
 * 
 * <p>Java class for SPICE_Kernel complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="SPICE_Kernel">
 *   <complexContent>
 *     <extension base="{http://pds.nasa.gov/pds4/pds/v1}Parsable_Byte_Stream">
 *       <sequence>
 *         <element name="kernel_type" type="{http://pds.nasa.gov/pds4/pds/v1}kernel_type"/>
 *         <element name="encoding_type" type="{http://pds.nasa.gov/pds4/pds/v1}encoding_type"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPICE_Kernel", propOrder = {
    "kernelType",
    "encodingType"
})
public class SPICEKernel
    extends ParsableByteStream
{

    @XmlElement(name = "kernel_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String kernelType;
    @XmlElement(name = "encoding_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String encodingType;

    /**
     * Gets the value of the kernelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKernelType() {
        return kernelType;
    }

    /**
     * Sets the value of the kernelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKernelType(String value) {
        this.kernelType = value;
    }

    /**
     * Gets the value of the encodingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncodingType() {
        return encodingType;
    }

    /**
     * Sets the value of the encodingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncodingType(String value) {
        this.encodingType = value;
    }

}
