//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Telescope class provides coordinates and
 *         parameters for terrestrial, ground-based
 *         telescopes.
 * 
 * <p>Java class for Telescope complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Telescope">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="aperture" type="{http://pds.nasa.gov/pds4/pds/v1}aperture"/>
 *         <element name="telescope_longitude" type="{http://pds.nasa.gov/pds4/pds/v1}telescope_longitude" minOccurs="0"/>
 *         <element name="telescope_latitude" type="{http://pds.nasa.gov/pds4/pds/v1}telescope_latitude" minOccurs="0"/>
 *         <element name="telescope_altitude" type="{http://pds.nasa.gov/pds4/pds/v1}telescope_altitude" minOccurs="0"/>
 *         <element name="altitude" type="{http://pds.nasa.gov/pds4/pds/v1}altitude" minOccurs="0"/>
 *         <element name="coordinate_source" type="{http://pds.nasa.gov/pds4/pds/v1}coordinate_source" minOccurs="0"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Telescope", propOrder = {
    "aperture",
    "telescopeLongitude",
    "telescopeLatitude",
    "telescopeAltitude",
    "altitude",
    "coordinateSource",
    "description"
})
public class Telescope {

    @XmlElement(required = true)
    protected Aperture aperture;
    @XmlElement(name = "telescope_longitude")
    protected TelescopeLongitude telescopeLongitude;
    @XmlElement(name = "telescope_latitude")
    protected TelescopeLatitude telescopeLatitude;
    @XmlElement(name = "telescope_altitude")
    protected TelescopeAltitude telescopeAltitude;
    protected Altitude altitude;
    @XmlElement(name = "coordinate_source")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String coordinateSource;
    protected String description;

    /**
     * Gets the value of the aperture property.
     * 
     * @return
     *     possible object is
     *     {@link Aperture }
     *     
     */
    public Aperture getAperture() {
        return aperture;
    }

    /**
     * Sets the value of the aperture property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aperture }
     *     
     */
    public void setAperture(Aperture value) {
        this.aperture = value;
    }

    /**
     * Gets the value of the telescopeLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link TelescopeLongitude }
     *     
     */
    public TelescopeLongitude getTelescopeLongitude() {
        return telescopeLongitude;
    }

    /**
     * Sets the value of the telescopeLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelescopeLongitude }
     *     
     */
    public void setTelescopeLongitude(TelescopeLongitude value) {
        this.telescopeLongitude = value;
    }

    /**
     * Gets the value of the telescopeLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link TelescopeLatitude }
     *     
     */
    public TelescopeLatitude getTelescopeLatitude() {
        return telescopeLatitude;
    }

    /**
     * Sets the value of the telescopeLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelescopeLatitude }
     *     
     */
    public void setTelescopeLatitude(TelescopeLatitude value) {
        this.telescopeLatitude = value;
    }

    /**
     * Gets the value of the telescopeAltitude property.
     * 
     * @return
     *     possible object is
     *     {@link TelescopeAltitude }
     *     
     */
    public TelescopeAltitude getTelescopeAltitude() {
        return telescopeAltitude;
    }

    /**
     * Sets the value of the telescopeAltitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelescopeAltitude }
     *     
     */
    public void setTelescopeAltitude(TelescopeAltitude value) {
        this.telescopeAltitude = value;
    }

    /**
     * Gets the value of the altitude property.
     * 
     * @return
     *     possible object is
     *     {@link Altitude }
     *     
     */
    public Altitude getAltitude() {
        return altitude;
    }

    /**
     * Sets the value of the altitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Altitude }
     *     
     */
    public void setAltitude(Altitude value) {
        this.altitude = value;
    }

    /**
     * Gets the value of the coordinateSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordinateSource() {
        return coordinateSource;
    }

    /**
     * Sets the value of the coordinateSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordinateSource(String value) {
        this.coordinateSource = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
