//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Transfer_Manifest class defines a table that
 *         maps product LIDVIDs to the file_specificaition_names of the
 *         products' XML label files.
 * 
 * <p>Java class for Transfer_Manifest complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Transfer_Manifest">
 *   <complexContent>
 *     <restriction base="{http://pds.nasa.gov/pds4/pds/v1}Table_Character">
 *       <sequence>
 *         <element name="name" type="{http://pds.nasa.gov/pds4/pds/v1}name" minOccurs="0"/>
 *         <element name="local_identifier" type="{http://pds.nasa.gov/pds4/pds/v1}local_identifier" minOccurs="0"/>
 *         <element name="md5_checksum" type="{http://pds.nasa.gov/pds4/pds/v1}md5_checksum" minOccurs="0"/>
 *         <element name="offset" type="{http://pds.nasa.gov/pds4/pds/v1}offset"/>
 *         <element name="records" type="{http://pds.nasa.gov/pds4/pds/v1}records"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description" minOccurs="0"/>
 *         <element name="record_delimiter" type="{http://pds.nasa.gov/pds4/pds/v1}record_delimiter"/>
 *         <element name="Uniformly_Sampled" type="{http://pds.nasa.gov/pds4/pds/v1}Uniformly_Sampled" minOccurs="0"/>
 *         <element name="Record_Character" type="{http://pds.nasa.gov/pds4/pds/v1}Record_Character"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transfer_Manifest")
public class TransferManifest
    extends TableCharacter
{


}
