//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for Units_of_Angle</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="Units_of_Angle">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="arcmin"/>
 *     <enumeration value="arcsec"/>
 *     <enumeration value="deg"/>
 *     <enumeration value="hr"/>
 *     <enumeration value="mrad"/>
 *     <enumeration value="rad"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "Units_of_Angle")
@XmlEnum
public enum UnitsOfAngle {

    @XmlEnumValue("arcmin")
    ARCMIN("arcmin"),
    @XmlEnumValue("arcsec")
    ARCSEC("arcsec"),
    @XmlEnumValue("deg")
    DEG("deg"),
    @XmlEnumValue("hr")
    HR("hr"),
    @XmlEnumValue("mrad")
    MRAD("mrad"),
    @XmlEnumValue("rad")
    RAD("rad");
    private final String value;

    UnitsOfAngle(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static UnitsOfAngle fromValue(String v) {
        for (UnitsOfAngle c: UnitsOfAngle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
