//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Vector_Cartesian_3_Base class is the parent
 *         class of 3 element Cartesian vectors.
 * 
 * <p>Java class for Vector_Cartesian_3 complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Vector_Cartesian_3">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="reference_frame_id" type="{http://pds.nasa.gov/pds4/pds/v1}reference_frame_id"/>
 *         <element name="x" type="{http://pds.nasa.gov/pds4/pds/v1}x"/>
 *         <element name="y" type="{http://pds.nasa.gov/pds4/pds/v1}y"/>
 *         <element name="z" type="{http://pds.nasa.gov/pds4/pds/v1}z"/>
 *       </sequence>
 *       <attribute name="unit" use="required" type="{http://pds.nasa.gov/pds4/pds/v1}ASCII_Short_String_Collapsed" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Vector_Cartesian_3", propOrder = {
    "referenceFrameId",
    "x",
    "y",
    "z"
})
@XmlSeeAlso({
    VectorCartesian3Acceleration.class,
    VectorCartesian3Pointing.class,
    VectorCartesian3Position.class,
    VectorCartesian3Velocity.class
})
public class VectorCartesian3 {

    @XmlElement(name = "reference_frame_id", required = true)
    protected ReferenceFrameId referenceFrameId;
    protected double x;
    protected double y;
    protected double z;
    @XmlAttribute(name = "unit", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String unit;

    /**
     * Gets the value of the referenceFrameId property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceFrameId }
     *     
     */
    public ReferenceFrameId getReferenceFrameId() {
        return referenceFrameId;
    }

    /**
     * Sets the value of the referenceFrameId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceFrameId }
     *     
     */
    public void setReferenceFrameId(ReferenceFrameId value) {
        this.referenceFrameId = value;
    }

    /**
     * Gets the value of the x property.
     * 
     */
    public double getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     */
    public void setX(double value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     */
    public double getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     */
    public void setY(double value) {
        this.y = value;
    }

    /**
     * Gets the value of the z property.
     * 
     */
    public double getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     * 
     */
    public void setZ(double value) {
        this.z = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

}
