//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package info.oais.oaisif.pds;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Volume_PDS3 class is used to capture the
 *         volume information from the PDS3 Data Set
 *         Catalog.
 * 
 * <p>Java class for Volume_PDS3 complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Volume_PDS3">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="archive_status" type="{http://pds.nasa.gov/pds4/pds/v1}archive_status"/>
 *         <element name="archive_status_note" type="{http://pds.nasa.gov/pds4/pds/v1}archive_status_note"/>
 *         <element name="curating_node_id" type="{http://pds.nasa.gov/pds4/pds/v1}curating_node_id" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="medium_type" type="{http://pds.nasa.gov/pds4/pds/v1}medium_type"/>
 *         <element name="publication_date" type="{http://pds.nasa.gov/pds4/pds/v1}publication_date"/>
 *         <element name="volume_de_fullname" type="{http://pds.nasa.gov/pds4/pds/v1}volume_de_fullname"/>
 *         <element name="volume_format" type="{http://pds.nasa.gov/pds4/pds/v1}volume_format"/>
 *         <element name="volume_id" type="{http://pds.nasa.gov/pds4/pds/v1}volume_id"/>
 *         <element name="volume_name" type="{http://pds.nasa.gov/pds4/pds/v1}volume_name"/>
 *         <element name="volume_set_id" type="{http://pds.nasa.gov/pds4/pds/v1}volume_set_id"/>
 *         <element name="volume_size" type="{http://pds.nasa.gov/pds4/pds/v1}volume_size"/>
 *         <element name="volume_version_id" type="{http://pds.nasa.gov/pds4/pds/v1}volume_version_id"/>
 *         <element name="description" type="{http://pds.nasa.gov/pds4/pds/v1}description" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Volume_PDS3", propOrder = {
    "archiveStatus",
    "archiveStatusNote",
    "curatingNodeId",
    "mediumType",
    "publicationDate",
    "volumeDeFullname",
    "volumeFormat",
    "volumeId",
    "volumeName",
    "volumeSetId",
    "volumeSize",
    "volumeVersionId",
    "description"
})
public class VolumePDS3 {

    @XmlElement(name = "archive_status", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String archiveStatus;
    @XmlElement(name = "archive_status_note", required = true)
    protected String archiveStatusNote;
    @XmlElement(name = "curating_node_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> curatingNodeId;
    @XmlElement(name = "medium_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String mediumType;
    @XmlElement(name = "publication_date", required = true, nillable = true)
    protected PublicationDate publicationDate;
    @XmlElement(name = "volume_de_fullname", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String volumeDeFullname;
    @XmlElement(name = "volume_format", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String volumeFormat;
    @XmlElement(name = "volume_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String volumeId;
    @XmlElement(name = "volume_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String volumeName;
    @XmlElement(name = "volume_set_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String volumeSetId;
    @XmlElement(name = "volume_size", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger volumeSize;
    @XmlElement(name = "volume_version_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String volumeVersionId;
    protected String description;

    /**
     * Gets the value of the archiveStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchiveStatus() {
        return archiveStatus;
    }

    /**
     * Sets the value of the archiveStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchiveStatus(String value) {
        this.archiveStatus = value;
    }

    /**
     * Gets the value of the archiveStatusNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchiveStatusNote() {
        return archiveStatusNote;
    }

    /**
     * Sets the value of the archiveStatusNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchiveStatusNote(String value) {
        this.archiveStatusNote = value;
    }

    /**
     * Gets the value of the curatingNodeId property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the curatingNodeId property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCuratingNodeId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the curatingNodeId property.
     */
    public List<String> getCuratingNodeId() {
        if (curatingNodeId == null) {
            curatingNodeId = new ArrayList<>();
        }
        return this.curatingNodeId;
    }

    /**
     * Gets the value of the mediumType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediumType() {
        return mediumType;
    }

    /**
     * Sets the value of the mediumType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediumType(String value) {
        this.mediumType = value;
    }

    /**
     * Gets the value of the publicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationDate }
     *     
     */
    public PublicationDate getPublicationDate() {
        return publicationDate;
    }

    /**
     * Sets the value of the publicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationDate }
     *     
     */
    public void setPublicationDate(PublicationDate value) {
        this.publicationDate = value;
    }

    /**
     * Gets the value of the volumeDeFullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolumeDeFullname() {
        return volumeDeFullname;
    }

    /**
     * Sets the value of the volumeDeFullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolumeDeFullname(String value) {
        this.volumeDeFullname = value;
    }

    /**
     * Gets the value of the volumeFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolumeFormat() {
        return volumeFormat;
    }

    /**
     * Sets the value of the volumeFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolumeFormat(String value) {
        this.volumeFormat = value;
    }

    /**
     * Gets the value of the volumeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolumeId() {
        return volumeId;
    }

    /**
     * Sets the value of the volumeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolumeId(String value) {
        this.volumeId = value;
    }

    /**
     * Gets the value of the volumeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolumeName() {
        return volumeName;
    }

    /**
     * Sets the value of the volumeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolumeName(String value) {
        this.volumeName = value;
    }

    /**
     * Gets the value of the volumeSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolumeSetId() {
        return volumeSetId;
    }

    /**
     * Sets the value of the volumeSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolumeSetId(String value) {
        this.volumeSetId = value;
    }

    /**
     * Gets the value of the volumeSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVolumeSize() {
        return volumeSize;
    }

    /**
     * Sets the value of the volumeSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVolumeSize(BigInteger value) {
        this.volumeSize = value;
    }

    /**
     * Gets the value of the volumeVersionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolumeVersionId() {
        return volumeVersionId;
    }

    /**
     * Sets the value of the volumeVersionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolumeVersionId(String value) {
        this.volumeVersionId = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
